# Generated by Django 5.2.8 on 2025-11-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('peso', models.FloatField(help_text='Peso en Kg')),
                ('altura', models.FloatField(help_text='Altura en Metros')),
                ('fecha_nacimiento', models.DateField()),
                ('categoria', models.CharField(choices=[('K10', '10K Promocional'), ('K21', 'Media Maratón'), ('K42', 'Maratón'), ('ULTRA', 'Ultra Trail')], default='K10', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.FloatField(help_text='Km')),
                ('desnivel', models.IntegerField(help_text='Metros +')),
                ('tipo', models.CharField(choices=[('FONDO', 'Fondo'), ('CUESTAS', 'Cuestas'), ('VELOCIDAD', 'Velocidad')], max_length=20)),
                ('completado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
        ),
    ]
