# Generated by Django 5.2.8 on 2025-12-01 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_ciudad_alumno_email_alumno_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenamiento',
            old_name='fecha',
            new_name='fecha_asignada',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='desnivel',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='distancia',
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='descripcion_coach',
            field=models.TextField(blank=True, help_text='Detalles del ejercicio', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='desnivel_planificado_m',
            field=models.IntegerField(default=0, help_text='Metros positivos (+)'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='desnivel_real_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='distancia_planificada_km',
            field=models.FloatField(default=0, help_text='Kilómetros objetivo'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='distancia_real_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='fecha_ejecucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='feedback_alumno',
            field=models.TextField(blank=True, help_text='Comentarios post-entreno', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='garmin_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='rpe',
            field=models.IntegerField(blank=True, help_text='Escala de Esfuerzo Percibido (1-10)', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='strava_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='tiempo_planificado_min',
            field=models.IntegerField(default=0, help_text='Minutos objetivo'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='tiempo_real_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='titulo',
            field=models.CharField(default='Entrenamiento', help_text='Ej: Fondo largo en montaña', max_length=200),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='core.alumno'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tipo',
            field=models.CharField(choices=[('RUN', 'Running (Asfalto)'), ('TRAIL', 'Trail Running (Montaña)'), ('FUERZA', 'Gimnasio / Fuerza'), ('BICICLETA', 'Ciclismo'), ('DESCANSO', 'Día de Descanso')], default='RUN', max_length=20),
        ),
    ]
