# Generated by Django 5.2.8 on 2025-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_fecha_entrenamiento_fecha_asignada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno (ej: Series 1000m)', max_length=200)),
                ('tipo', models.CharField(choices=[('RUN', 'Running (Asfalto)'), ('TRAIL', 'Trail Running (Montaña)'), ('FUERZA', 'Gimnasio / Fuerza'), ('BICICLETA', 'Ciclismo'), ('DESCANSO', 'Día de Descanso')], default='RUN', max_length=20)),
                ('titulo_default', models.CharField(help_text='Título para el alumno', max_length=200)),
                ('descripcion_default', models.TextField(blank=True, help_text='Instrucciones')),
                ('distancia_default_km', models.FloatField(default=0)),
                ('tiempo_default_min', models.IntegerField(default=0)),
                ('desnivel_default_m', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Librería',
                'verbose_name_plural': 'Librería de Entrenamientos',
            },
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='descripcion_coach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='desnivel_planificado_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='distancia_planificada_km',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='feedback_alumno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='rpe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tiempo_planificado_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='titulo',
            field=models.CharField(default='Entrenamiento', max_length=200),
        ),
    ]
