# Generated by Django 5.2.8 on 2025-12-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plantillaentrenamiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillaentrenamiento',
            options={'verbose_name': '📂 Plantilla de Librería', 'verbose_name_plural': '📂 Librería de Entrenamientos'},
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='descripcion_coach',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='desnivel_planificado_m',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='distancia_planificada_km',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='fecha_ejecucion',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='tiempo_planificado_min',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='plantillaentrenamiento',
            name='descripcion_default',
        ),
        migrations.RemoveField(
            model_name='plantillaentrenamiento',
            name='desnivel_default_m',
        ),
        migrations.RemoveField(
            model_name='plantillaentrenamiento',
            name='distancia_default_km',
        ),
        migrations.RemoveField(
            model_name='plantillaentrenamiento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='plantillaentrenamiento',
            name='tiempo_default_min',
        ),
        migrations.RemoveField(
            model_name='plantillaentrenamiento',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='plantillaentrenamiento',
            name='titulo_default',
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='plantilla_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plantillaentrenamiento'),
        ),
        migrations.AddField(
            model_name='plantillaentrenamiento',
            name='deporte',
            field=models.CharField(choices=[('RUN', 'Running (Calle)'), ('TRAIL', 'Trail Running (Montaña)'), ('CYCLING', 'Ciclismo / Ruta'), ('MTB', 'Ciclismo / MTB'), ('SWIMMING', 'Natación'), ('STRENGTH', 'Fuerza / Gimnasio'), ('CARDIO', 'Cardio / Funcional'), ('INDOOR_BIKE', 'Bici Fija / Rodillo'), ('REST', 'Descanso Total'), ('OTHER', 'Otro')], default='RUN', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillaentrenamiento',
            name='descripcion_global',
            field=models.TextField(blank=True, help_text='Descripción completa, enlaces a YouTube, estrategia, nutrición...'),
        ),
        migrations.AddField(
            model_name='plantillaentrenamiento',
            name='enlace_video',
            field=models.URLField(blank=True, help_text='Link a YouTube/Vimeo explicativo', null=True),
        ),
        migrations.AddField(
            model_name='plantillaentrenamiento',
            name='etiqueta_dificultad',
            field=models.CharField(choices=[('EASY', '🟢 Suave'), ('MODERATE', '🟡 Moderado'), ('HARD', '🔴 Duro'), ('EXTREME', '⚫ Extremo')], default='MODERATE', max_length=20),
        ),
        migrations.AddField(
            model_name='plantillaentrenamiento',
            name='titulo',
            field=models.CharField(default='Plantilla Base', help_text='Ej: Series 10x400m + Umbral', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='categoria',
            field=models.CharField(choices=[('K10', '10K'), ('K21', '21K'), ('K42', '42K'), ('ULTRA', 'Ultra')], default='K10', max_length=10),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='BloqueEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de ejecución del bloque')),
                ('nombre_bloque', models.CharField(default='Bloque Principal', help_text='Ej: Calentamiento, Series Principales', max_length=100)),
                ('repeticiones', models.PositiveIntegerField(default=1, help_text='¿Cuántas veces se repite este bloque?')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='core.plantillaentrenamiento')),
            ],
            options={
                'verbose_name': '🔁 Bloque / Repetición',
                'verbose_name_plural': '🔁 Bloques del Entrenamiento',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PasoEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('titulo_paso', models.CharField(blank=True, help_text='Ej: Trote suave, A fondo, Recuperación parada', max_length=100)),
                ('fase', models.CharField(choices=[('WARMUP', '🔥 Calentamiento'), ('ACTIVE', '⚡ Trabajo / Intervalo'), ('RECOVERY', '💤 Recuperación / Pausa'), ('COOLDOWN', '❄️ Vuelta a la calma'), ('OTHER', '📝 Nota / Técnica')], default='ACTIVE', max_length=20)),
                ('tipo_duracion', models.CharField(choices=[('DISTANCE', 'Distancia'), ('TIME', 'Tiempo'), ('LAP_BUTTON', 'Presionar Lap'), ('CALORIES', 'Calorías'), ('OPEN', 'Abierto / Sin límite')], default='DISTANCE', max_length=20)),
                ('valor_duracion', models.FloatField(default=0, help_text='Cantidad (km, minutos, etc)')),
                ('unidad_duracion', models.CharField(choices=[('KM', 'Kilómetros'), ('M', 'Metros'), ('MI', 'Millas'), ('MIN', 'Minutos'), ('SEC', 'Segundos'), ('HR', 'Horas'), ('CAL', 'Kcal'), ('N/A', '-')], default='KM', max_length=10)),
                ('tipo_objetivo', models.CharField(choices=[('NONE', 'Sin Objetivo'), ('PACE', 'Ritmo (min/km)'), ('HEART_RATE', 'Frecuencia Cardíaca'), ('POWER', 'Potencia (Watts)'), ('RPE', 'Sensación (1-10)'), ('CADENCE', 'Cadencia (rpm)')], default='NONE', max_length=20)),
                ('zona_objetivo', models.CharField(blank=True, choices=[('Z1', 'Z1 - Recuperación'), ('Z2', 'Z2 - Aeróbico Base'), ('Z3', 'Z3 - Ritmo Tempo'), ('Z4', 'Z4 - Umbral Lactato'), ('Z5', 'Z5 - VO2 Max'), ('Z6', 'Z6 - Anaeróbico'), ('Z7', 'Z7 - Neuromuscular')], help_text='Si eliges Zona FC', max_length=5, null=True)),
                ('valor_objetivo_min', models.FloatField(blank=True, help_text='Mínimo (Ritmo/Watts/FC)', null=True)),
                ('valor_objetivo_max', models.FloatField(blank=True, help_text='Máximo (Ritmo/Watts/FC)', null=True)),
                ('nota_paso', models.CharField(blank=True, help_text='Nota corta que vibra en el reloj', max_length=200)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='core.bloqueentrenamiento')),
            ],
            options={
                'verbose_name': '👟 Paso',
                'verbose_name_plural': '👟 Pasos',
                'ordering': ['orden'],
            },
        ),
    ]
