# Generated by Django 5.2.8 on 2025-12-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_plantillaentrenamiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloqueentrenamiento',
            options={'ordering': ['orden'], 'verbose_name': 'Estructura', 'verbose_name_plural': 'Estructura'},
        ),
        migrations.AlterModelOptions(
            name='pasoentrenamiento',
            options={'ordering': ['orden'], 'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos del Bloque'},
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='tipo_duracion',
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='tipo_objetivo',
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='valor_objetivo_max',
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='valor_objetivo_min',
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='zona_objetivo',
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='objetivo',
            field=models.CharField(choices=[('NONE', 'Sin Objetivo'), ('RPE_1', '1 - Muy Suave (Recuperación)'), ('RPE_2', '2 - Suave (Aeróbico Extensivo)'), ('RPE_3', '3 - Moderado (Aeróbico Medio)'), ('RPE_4', '4 - Ritmo Maratón'), ('RPE_5', '5 - Umbral Anaeróbico'), ('RPE_6', '6 - VO2 Max'), ('RPE_7', '7 - Capacidad Anaeróbica'), ('RPE_8', '8 - Sprint'), ('RPE_9', '9 - Neuromuscular'), ('RPE_10', '10 - Máximo Esfuerzo'), ('ZONA_FC', 'Zona Frecuencia Cardíaca'), ('PACE', 'Ritmo Objetivo')], default='RPE_2', max_length=20, verbose_name='Intensidad'),
        ),
        migrations.AlterField(
            model_name='bloqueentrenamiento',
            name='nombre_bloque',
            field=models.CharField(blank=True, default='Bloque Estándar', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloqueentrenamiento',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bloqueentrenamiento',
            name='repeticiones',
            field=models.PositiveIntegerField(default=1, help_text='Repeticiones de este bloque'),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='fase',
            field=models.CharField(choices=[('WARMUP', '🔥 Calentamiento'), ('ACTIVE', '⚡ Activo / Intervalo'), ('RECOVERY', '💤 Recuperación'), ('COOLDOWN', '❄️ Vuelta a la calma'), ('OTHER', '📝 Nota Técnica')], default='ACTIVE', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='nota_paso',
            field=models.CharField(blank=True, help_text='Nota extra', max_length=200),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='titulo_paso',
            field=models.CharField(blank=True, max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='unidad_duracion',
            field=models.CharField(choices=[('KM', 'km'), ('METERS', 'metros'), ('MIN', 'minutos'), ('SEC', 'segundos')], default='KM', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='valor_duracion',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='plantillaentrenamiento',
            name='descripcion_global',
            field=models.TextField(blank=True, help_text='Descripción completa, enlaces, estrategia. ¡Usa emojis! 🚴\u200d♂️🏃\u200d♀️'),
        ),
    ]
