# Generated by Django 5.2.8 on 2025-12-02 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bloqueentrenamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueentrenamiento',
            name='entrenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques_reales', to='core.entrenamiento'),
        ),
        migrations.AlterField(
            model_name='bloqueentrenamiento',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='core.plantillaentrenamiento'),
        ),
    ]
