# Generated by Django 5.2.8 on 2025-12-02 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bloqueentrenamiento_entrenamiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Patagonia Run 2025', max_length=200)),
                ('tipo', models.CharField(choices=[('TRAIL', 'Trail Running'), ('CALLE', 'Calle / Asfalto'), ('ULTRA', 'Ultra Distancia'), ('TRIATLON', 'Triatlón'), ('AVENTURA', 'Carrera de Aventura'), ('OTRO', 'Otro Evento')], default='TRAIL', max_length=20)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(blank=True, help_text='Ciudad / Provincia', max_length=100)),
                ('distancia_km', models.FloatField(help_text='Distancia total')),
                ('desnivel_positivo_m', models.IntegerField(default=0, help_text='Metros acumulados (+)')),
                ('web_oficial', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='fase',
            field=models.CharField(choices=[('WARMUP', '🔥 Calentamiento'), ('ACTIVE', '⚡ Intervalo'), ('RECOVERY', '💤 Recuperación'), ('COOLDOWN', '❄️ Vuelta a la calma'), ('OTHER', '📝 Nota Técnica'), ('COOLDOWN', '🚶🏼Caminata')], default='ACTIVE', max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='InscripcionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INSCRITO', '✅ Inscrito'), ('INTERESADO', '👀 Interesado / Objetivo Posible'), ('BAJA', '❌ Baja / No corre'), ('FINALIZADO', '🏅 Finalizó'), ('DNF', '💀 Abandonó (DNF)')], default='INSCRITO', max_length=20)),
                ('prioridad', models.CharField(choices=[('A', 'A - Principal'), ('B', 'B - Preparatoria'), ('C', 'C - Entrenamiento')], default='A', help_text='Importancia de la carrera', max_length=1)),
                ('tiempo_oficial', models.DurationField(blank=True, help_text='Tiempo final hh:mm:ss', null=True)),
                ('posicion_general', models.IntegerField(blank=True, null=True)),
                ('posicion_categoria', models.IntegerField(blank=True, null=True)),
                ('feedback_carrera', models.TextField(blank=True, help_text='Análisis post-carrera del alumno')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='core.alumno')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptos', to='core.carrera')),
            ],
            options={
                'verbose_name': '🏅 Inscripción / Objetivo',
                'verbose_name_plural': '🏅 Calendario de Carreras',
                'unique_together': {('alumno', 'carrera')},
            },
        ),
    ]
