# Generated by Django 5.2.8 on 2025-12-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carrera_alter_pasoentrenamiento_fase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenamiento',
            options={'ordering': ['-fecha_asignada']},
        ),
        migrations.AlterModelOptions(
            name='inscripcioncarrera',
            options={'verbose_name': '🏅 Inscripción / Objetivo', 'verbose_name_plural': ' Calendario de Carreras'},
        ),
        migrations.AlterModelOptions(
            name='pasoentrenamiento',
            options={},
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='nota_paso',
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='unidad_duracion',
        ),
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='valor_duracion',
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='tipo_duracion',
            field=models.CharField(choices=[('DISTANCE', 'Distancia'), ('TIME', 'Tiempo'), ('LAP_BUTTON', 'Presionar Lap'), ('CALORIES', 'Calorías'), ('OPEN', 'Abierto / Sin límite')], default='TIME', max_length=20, verbose_name='Tipo Duración'),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='fase',
            field=models.CharField(choices=[('WARMUP', '🔥 Calentamiento'), ('ACTIVE', '⚡ Activo / Intervalo'), ('RECOVERY', '💤 Recuperación'), ('COOLDOWN', '❄️ Vuelta a la calma'), ('OTHER', '📝 Nota Técnica')], default='ACTIVE', max_length=20, verbose_name='Tipo'),
        ),
    ]
