# Generated by Django 5.2.8 on 2025-12-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_entrenamiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasoentrenamiento',
            options={'ordering': ['orden'], 'verbose_name': 'Paso', 'verbose_name_plural': 'Pasos del Bloque'},
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='nota_paso',
            field=models.CharField(blank=True, help_text='Nota extra', max_length=200),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='objetivo',
            field=models.CharField(choices=[('NONE', 'Sin Objetivo'), ('RPE_1', '1 - Muy Suave (Recuperación)'), ('RPE_2', '2 - Suave (Aeróbico Extensivo)'), ('RPE_3', '3 - Moderado (Aeróbico Medio)'), ('RPE_4', '4 - Ritmo Maratón'), ('RPE_5', '5 - Umbral Anaeróbico'), ('RPE_6', '6 - VO2 Max'), ('RPE_7', '7 - Capacidad Anaeróbica'), ('RPE_8', '8 - Sprint'), ('RPE_9', '9 - Neuromuscular'), ('RPE_10', '10 - Máximo Esfuerzo'), ('ZONA_FC', 'Zona Frecuencia Cardíaca'), ('PACE', 'Ritmo Objetivo')], default='RPE_2', max_length=20, verbose_name='Intensidad'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='unidad_duracion',
            field=models.CharField(choices=[('KM', 'km'), ('METERS', 'metros'), ('MIN', 'minutos'), ('SEC', 'segundos')], default='KM', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='valor_duracion',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
    ]
