# Generated by Django 5.2.8 on 2025-12-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pasoentrenamiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='tipo',
            field=models.CharField(choices=[('TRAIL', 'Trail Running'), ('ULTRA', 'Ultra Distancia'), ('CALLE', 'Calle / Asfalto'), ('CICLISMO', 'Ciclismo'), ('TRIATLON', 'Triatlón'), ('AVENTURA', 'Carrera de Aventura'), ('OTRO', 'Otro Evento')], default='TRAIL', max_length=20),
        ),
    ]
