# Generated by Django 5.2.8 on 2025-12-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_carrera_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fcm',
            field=models.IntegerField(default=180, help_text='Frecuencia Cardíaca Máxima'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fcreposo',
            field=models.IntegerField(default=50, help_text='Frecuencia Cardíaca en Reposo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ftp',
            field=models.IntegerField(default=200, help_text='Potencia Umbral Funcional (Watts)'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='intensity_factor',
            field=models.FloatField(blank=True, help_text='IF: Intensidad relativa al FTP', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='kilojoules',
            field=models.IntegerField(blank=True, help_text='Trabajo total realizado', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='load_final',
            field=models.FloatField(blank=True, help_text='Carga Final (Prioridad: TSS > TRIMP > RPE)', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='normalized_power',
            field=models.IntegerField(blank=True, help_text='NP: Potencia Normalizada estimada', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='trimp',
            field=models.FloatField(blank=True, help_text='Training Impulse (Carga Cardíaca)', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='tss',
            field=models.FloatField(blank=True, help_text='Training Stress Score (Carga de Potencia)', null=True),
        ),
    ]
