# Generated by Django 5.2.8 on 2025-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alumno_fcm_alumno_fcreposo_alumno_ftp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='frecuencia_cardiaca_promedio',
            field=models.IntegerField(blank=True, help_text='Pulsaciones medias (Avg HR)', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='potencia_promedio',
            field=models.IntegerField(blank=True, help_text='Vatios medios (Avg Watts)', null=True),
        ),
    ]
