# Generated by Django 5.2.8 on 2025-12-05 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entrenamiento_frecuencia_cardiaca_promedio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillaentrenamiento',
            options={'verbose_name': '📂 Plantilla de Librería', 'verbose_name_plural': 'Librería de Entrenamientos'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='categoria',
            field=models.CharField(choices=[('K21', '21K'), ('K42', '42K'), ('ULTRA', 'Ultra')], default='K21', max_length=10),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(help_text='ID único de la actividad en Strava', unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('distancia', models.FloatField(help_text='Distancia en metros')),
                ('tiempo_movimiento', models.IntegerField(help_text='Tiempo en segundos')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio (Local)')),
                ('tipo_deporte', models.CharField(help_text='Run, Ride, Swim, etc.', max_length=50)),
                ('desnivel_positivo', models.FloatField(blank=True, default=0.0, null=True)),
                ('ritmo_promedio', models.FloatField(blank=True, help_text='Metros por segundo', null=True)),
                ('mapa_polilinea', models.TextField(blank=True, help_text='Código del mapa para dibujar', null=True)),
                ('datos_brutos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_strava', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad Importada',
                'verbose_name_plural': 'Actividades Importadas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
