# Generated by Django 5.2.8 on 2025-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_plantillaentrenamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='distancia_planificada_km',
            field=models.FloatField(default=0, help_text='Instantánea del plan'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='porcentaje_cumplimiento',
            field=models.IntegerField(default=0, help_text='Qué % de lo planificado se cumplió'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='tiempo_planificado_min',
            field=models.IntegerField(default=0, help_text='Instantánea del plan'),
        ),
    ]
