# Generated by Django 5.2.8 on 2025-12-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_entrenamiento_distancia_planificada_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='carbohidratos_hora',
            field=models.IntegerField(default=0, help_text='Gramos de CHO por hora recomendados'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='estrategia_nutricional',
            field=models.TextField(blank=True, help_text='Qué comer antes/durante'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='hidratacion_hora',
            field=models.IntegerField(default=0, help_text='Mililitros de líquido por hora'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='distancia_planificada_km',
            field=models.FloatField(default=0, help_text='Instantánea del plan (Auto-calculado)'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tiempo_planificado_min',
            field=models.IntegerField(default=0, help_text='Instantánea del plan (Auto-calculado)'),
        ),
    ]
