# Generated by Django 5.2.8 on 2025-12-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_entrenamiento_carbohidratos_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='bloqueentrenamiento',
            options={'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='inscripcioncarrera',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pasoentrenamiento',
            options={'ordering': ['orden']},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='distancia',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='mapa_polilinea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='ritmo_promedio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='strava_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_movimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_deporte',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloqueentrenamiento',
            name='repeticiones',
            field=models.PositiveIntegerField(default=1, help_text='Repeticiones'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='desnivel_positivo_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='distancia_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='lugar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='carbohidratos_hora',
            field=models.IntegerField(default=0, help_text='Gramos de CHO por hora'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='frecuencia_cardiaca_promedio',
            field=models.IntegerField(blank=True, help_text='Pulsaciones medias', null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='intensity_factor',
            field=models.FloatField(blank=True, help_text='IF', null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='kilojoules',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='load_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='normalized_power',
            field=models.IntegerField(blank=True, help_text='NP', null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='potencia_promedio',
            field=models.IntegerField(blank=True, help_text='Vatios medios', null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='trimp',
            field=models.FloatField(blank=True, help_text='Training Impulse', null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tss',
            field=models.FloatField(blank=True, help_text='Training Stress Score', null=True),
        ),
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='estado',
            field=models.CharField(default='INSCRITO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='feedback_carrera',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='prioridad',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='tiempo_oficial',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='fase',
            field=models.CharField(choices=[('WARMUP', '🔥 Calentamiento'), ('ACTIVE', '⚡ Activo / Intervalo'), ('RECOVERY', '💤 Recuperación'), ('COOLDOWN', '❄️ Vuelta a la calma'), ('OTHER', '📝 Nota Técnica')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='nota_paso',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='objetivo',
            field=models.CharField(choices=[('NONE', 'Sin Objetivo'), ('RPE_1', '1 - Muy Suave (Recuperación)'), ('RPE_2', '2 - Suave (Aeróbico Extensivo)'), ('RPE_3', '3 - Moderado (Aeróbico Medio)'), ('RPE_4', '4 - Ritmo Maratón'), ('RPE_5', '5 - Umbral Anaeróbico'), ('RPE_6', '6 - VO2 Max'), ('RPE_7', '7 - Capacidad Anaeróbica'), ('RPE_8', '8 - Sprint'), ('RPE_9', '9 - Neuromuscular'), ('RPE_10', '10 - Máximo Esfuerzo'), ('ZONA_FC', 'Zona Frecuencia Cardíaca'), ('PACE', 'Ritmo Objetivo')], default='RPE_2', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='tipo_duracion',
            field=models.CharField(choices=[('DISTANCE', 'Distancia'), ('TIME', 'Tiempo'), ('LAP_BUTTON', 'Presionar Lap'), ('CALORIES', 'Calorías'), ('OPEN', 'Abierto / Sin límite')], default='TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='titulo_paso',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='unidad_duracion',
            field=models.CharField(choices=[('KM', 'km'), ('METERS', 'metros'), ('MIN', 'minutos'), ('SEC', 'segundos')], default='KM', max_length=10),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='valor_duracion',
            field=models.FloatField(default=0),
        ),
    ]
