# Generated by Django 5.2.8 on 2025-12-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='altura',
            field=models.FloatField(help_text='Altura en Metros'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fcm',
            field=models.IntegerField(default=180, help_text='FC Máxima'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fcreposo',
            field=models.IntegerField(default=50, help_text='FC Reposo'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ftp',
            field=models.IntegerField(default=200, help_text='FTP (Watts)'),
        ),
        migrations.AlterField(
            model_name='bloqueentrenamiento',
            name='nombre_bloque',
            field=models.CharField(default='Bloque', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloqueentrenamiento',
            name='repeticiones',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='carbohidratos_hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='distancia_planificada_km',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='estrategia_nutricional',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='frecuencia_cardiaca_promedio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='hidratacion_hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='intensity_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='normalized_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='porcentaje_cumplimiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='potencia_promedio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tiempo_planificado_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='trimp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='objetivo',
            field=models.CharField(choices=[('NONE', 'Sin Objetivo'), ('RPE_1', '1 - Muy Suave'), ('RPE_2', '2 - Suave'), ('RPE_3', '3 - Moderado'), ('RPE_4', '4 - Ritmo Maratón'), ('RPE_5', '5 - Umbral'), ('RPE_6', '6 - VO2 Max'), ('RPE_7', '7 - Anaeróbico'), ('RPE_8', '8 - Sprint'), ('RPE_9', '9 - Neuromuscular'), ('RPE_10', '10 - Máximo'), ('ZONA_FC', 'Zona FC'), ('PACE', 'Ritmo'), ('WATTS', 'Potencia')], default='RPE_2', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='unidad_duracion',
            field=models.CharField(choices=[('KM', 'Kilómetros'), ('METERS', 'Metros'), ('MILES', 'Millas'), ('MIN', 'Minutos'), ('SEC', 'Segundos'), ('HOURS', 'Horas'), ('N/A', '-')], default='MIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='plantillaentrenamiento',
            name='descripcion_global',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plantillaentrenamiento',
            name='enlace_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantillaentrenamiento',
            name='etiqueta_dificultad',
            field=models.CharField(choices=[('EASY', '🟢 Suave'), ('MODERATE', '🟡 Moderado'), ('HARD', '🔴 Duro')], default='MODERATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='plantillaentrenamiento',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
