# Generated by Django 5.2.8 on 2025-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_alumno_altura_alter_alumno_fcm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='feedback_ia',
            field=models.TextField(blank=True, help_text='Análisis generado por IA', null=True),
        ),
    ]
