# Generated by Django 5.2.8 on 2025-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_entrenamiento_feedback_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='descripcion_detallada',
            field=models.TextField(blank=True, help_text='Instrucciones técnicas, terreno, etc.', null=True),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='desnivel_planificado_m',
            field=models.IntegerField(default=0, help_text='Metros positivos acumulados (D+)'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='intensidad_planificada',
            field=models.CharField(choices=[('Z1', 'Z1 - Recuperación'), ('Z2', 'Z2 - Aeróbico Suave'), ('Z3', 'Z3 - Tempo / Ritmo'), ('Z4', 'Z4 - Umbral Lactato'), ('Z5', 'Z5 - VO2 Max')], default='Z2', max_length=50),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='rpe_planificado',
            field=models.IntegerField(default=0, help_text='Esfuerzo Percibido Objetivo (1-10)'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='tipo_actividad',
            field=models.CharField(choices=[('RUN', 'Running (Calle)'), ('TRAIL', 'Trail Running (Montaña)'), ('CYCLING', 'Ciclismo / Ruta'), ('MTB', 'Ciclismo / MTB'), ('SWIMMING', 'Natación'), ('STRENGTH', 'Fuerza / Gimnasio'), ('CARDIO', 'Cardio / Funcional'), ('INDOOR_BIKE', 'Bici Fija / Rodillo'), ('REST', 'Descanso Total'), ('OTHER', 'Otro')], default='RUN', help_text='Tipo de deporte planificado', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='rpe',
            field=models.IntegerField(blank=True, help_text='RPE Real sentido por el atleta', null=True),
        ),
    ]
