# Generated by Django 5.2.8 on 2025-12-09 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_entrenamiento_descripcion_detallada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillaentrenamiento',
            options={'verbose_name': '📂 Plantilla de Librería', 'verbose_name_plural': '📂 Librería de Entrenamientos'},
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='actualizado_en',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='alumno',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
