# Generated by Django 5.2.8 on 2025-12-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_plantillaentrenamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='strava_athlete_id',
            field=models.CharField(blank=True, help_text='ID numérico de Strava (Ej: 68831859)', max_length=50, null=True, unique=True),
        ),
    ]
