# Generated by Django 5.2.8 on 2025-12-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alumno_strava_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='itra_score',
            field=models.IntegerField(default=0, help_text='Puntuación General ITRA', verbose_name='ITRA Score'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_10k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pronóstico 10K'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_21k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pronóstico 21K'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_42k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pronóstico 42K'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_ultra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pronóstico 160K (Miler)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='vam_actual',
            field=models.FloatField(default=0, help_text='Velocidad Aeróbica Máxima (km/h) en plano', verbose_name='VAM (Plano)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='velocidad_pico',
            field=models.FloatField(default=0, help_text='Velocidad Pico (km/h) al 10%', verbose_name='Vpico (km/h)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='velocidad_uae',
            field=models.FloatField(default=0, help_text='Velocidad en Umbral Aeróbico (km/h) en subida', verbose_name='UAE (km/h)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='velocidad_uanae',
            field=models.FloatField(default=0, help_text='Velocidad en Umbral Anaeróbico (km/h) en subida', verbose_name='UANAE (km/h)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='vo2_max',
            field=models.FloatField(default=0, help_text='VO2max (ml/kg/min)', verbose_name='VO2 Máx'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ftp',
            field=models.IntegerField(default=200, help_text='FTP (Watts) - Ciclismo/Potencia'),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='objetivo',
            field=models.CharField(choices=[('NONE', 'Sin Objetivo'), ('RPE_1', '1 - Muy Suave'), ('RPE_2', '2 - Suave'), ('RPE_3', '3 - Moderado'), ('RPE_4', '4 - Ritmo Maratón'), ('RPE_5', '5 - Umbral'), ('RPE_6', '6 - VO2 Max'), ('RPE_7', '7 - Anaeróbico'), ('RPE_8', '8 - Sprint'), ('RPE_9', '9 - Neuromuscular'), ('RPE_10', '10 - Máximo'), ('ZONA_FC', 'Zona Frecuencia Cardíaca'), ('PACE', 'Ritmo'), ('WATTS', 'Potencia')], default='RPE_2', max_length=20),
        ),
    ]
