# Generated by Django 5.2.8 on 2025-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alumno_itra_score_alumno_prediccion_10k_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='prediccion_ultra',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='inscripcioncarrera',
            name='posicion_categoria',
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_trail_100k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ultra 100K (+5000m)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_trail_160k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Miler 160K (+8000m)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_trail_21k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Trail 21K (+1000m)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_trail_42k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Trail 42K (+2000m)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_trail_60k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ultra 60K (+3000m)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='prediccion_trail_80k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ultra 80K (+4000m)'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='desnivel_negativo_m',
            field=models.IntegerField(default=0, help_text='Metros D- (Importante para daño muscular)'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='factor_terreno',
            field=models.FloatField(choices=[(1.0, '🛣️ Asfalto / Pista (Rápido)'), (1.05, '🌲 Sendero Corrible (Pista forestal)'), (1.15, '⛰️ Trail Técnico Medio (Raíces/Rocas)'), (1.25, '🧗 Técnico Duro / Skyrunning (Mucha piedra/Trepadas)'), (1.4, '🧟 Jungla / Barro Extremo / Nieve')], default=1.05, help_text='¿Qué tan técnico es el terreno? (1.0=Calle, 1.4=Extremo)'),
        ),
        migrations.AddField(
            model_name='inscripcioncarrera',
            name='estrategia_nutricional',
            field=models.TextField(blank=True, verbose_name='🍔 Estrategia Nutricional'),
        ),
        migrations.AddField(
            model_name='inscripcioncarrera',
            name='tiempo_estimado_ia',
            field=models.CharField(blank=True, max_length=20, verbose_name='⏱️ Tiempo Estimado IA'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_10k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Calle 10K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_21k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Calle 21K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_42k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Calle 42K'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='desnivel_positivo_m',
            field=models.IntegerField(default=0, help_text='Metros D+'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='distancia_km',
            field=models.FloatField(help_text='Distancia Real'),
        ),
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='estado',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('INTERESADO', 'Interesado'), ('FINALIZADO', 'Finalizado')], default='INSCRITO', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='prioridad',
            field=models.CharField(choices=[('A', 'A (Principal)'), ('B', 'B (Secundaria)'), ('C', 'C (Entreno)')], default='A', max_length=1),
        ),
    ]
