# Generated by Django 5.2.8 on 2025-12-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_alumno_prediccion_ultra_remove_carrera_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='preferencia_alimentacion',
            field=models.CharField(choices=[('GELES', '⚡ Solo Geles/Isotónico (Pro)'), ('REAL', '🍎 Comida Real (Pasas, Membrillo, Bocadillos)'), ('MIX', '🔄 Mixto (Lo mejor de ambos mundos)')], default='MIX', max_length=10, verbose_name='Preferencia Nutricional'),
        ),
    ]
