# Generated by Django 5.2.8 on 2025-12-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alumno_preferencia_alimentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncarrera',
            name='objetivo_semanal_texto',
            field=models.TextField(blank=True, verbose_name='📉 Planificación Temporal'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_10k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pronóstico 10K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_21k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pronóstico 21K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_42k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pronóstico 42K'),
        ),
    ]
