# Generated by Django 5.2.8 on 2025-12-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_inscripcioncarrera_objetivo_semanal_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='test_1k_tiempo',
            field=models.DurationField(blank=True, help_text='Tiempo en 1000m a tope', null=True, verbose_name='Test 1000m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='test_5k_tiempo',
            field=models.DurationField(blank=True, help_text='Tiempo en 5km a tope (Llano)', null=True, verbose_name='Test 5k Llano'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='test_5k_trail_tiempo',
            field=models.DurationField(blank=True, help_text='Tiempo en 5km con +250m desnivel', null=True, verbose_name='Test 5k Cuesta'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='test_cooper_distancia',
            field=models.FloatField(default=0, help_text='Distancia en 12 min (km)', verbose_name='Test Cooper (Km)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_10k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Calle 10K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_21k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Calle 21K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_42k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Calle 42K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='vo2_max',
            field=models.FloatField(default=0, help_text='VO2max (ml/kg/min)', verbose_name='VO2 Máx (Calc)'),
        ),
    ]
