# Generated by Django 5.2.8 on 2025-12-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alumno_test_1k_tiempo_alumno_test_5k_tiempo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_1000m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 1000m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_100m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 100m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_1200m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 1200m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_1500m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 1500m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_1600m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 1600m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_2000m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 2000m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_200m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 200m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_250m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 250m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_400m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 400m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_500m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 500m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_600m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 600m'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ritmo_serie_800m',
            field=models.CharField(blank=True, max_length=20, verbose_name='Serie 800m'),
        ),
    ]
