# Generated by Django 5.2.8 on 2025-12-12 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alumno_ritmo_serie_1000m_alumno_ritmo_serie_100m_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantillaentrenamiento',
            options={'verbose_name': '📂 Plantilla de Librería'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Alumno Activo?'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apto_medico_al_dia',
            field=models.BooleanField(default=False, verbose_name='✅ Apto Médico al Día'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre Contacto Emergencia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='domingo_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='domingo_turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('MT', 'Mañana/Tarde'), ('TN', 'Tarde/Noche'), ('FULL', 'Todo el Día'), ('NO', '❌ NO DISPONIBLE')], default='FULL', max_length=5),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Alta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True, verbose_name='📅 Último Pago'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_vencimiento_apto',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento Apto'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=10, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='instagram',
            field=models.CharField(blank=True, help_text='Usuario sin @', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='jueves_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='jueves_turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('MT', 'Mañana/Tarde'), ('TN', 'Tarde/Noche'), ('FULL', 'Todo el Día'), ('NO', '❌ NO DISPONIBLE')], default='FULL', max_length=5),
        ),
        migrations.AddField(
            model_name='alumno',
            name='lesiones_alergias',
            field=models.TextField(blank=True, verbose_name='⚠️ Lesiones/Alergias'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='lunes_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='lunes_turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('MT', 'Mañana/Tarde'), ('TN', 'Tarde/Noche'), ('FULL', 'Todo el Día'), ('NO', '❌ NO DISPONIBLE')], default='FULL', max_length=5),
        ),
        migrations.AddField(
            model_name='alumno',
            name='martes_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='martes_turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('MT', 'Mañana/Tarde'), ('TN', 'Tarde/Noche'), ('FULL', 'Todo el Día'), ('NO', '❌ NO DISPONIBLE')], default='FULL', max_length=5),
        ),
        migrations.AddField(
            model_name='alumno',
            name='miercoles_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='miercoles_turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('MT', 'Mañana/Tarde'), ('TN', 'Tarde/Noche'), ('FULL', 'Todo el Día'), ('NO', '❌ NO DISPONIBLE')], default='FULL', max_length=5),
        ),
        migrations.AddField(
            model_name='alumno',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ocupación/Trabajo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='otros_deportes',
            field=models.CharField(blank=True, help_text='Ej: CrossFit, Natación', max_length=200, verbose_name='Deportes Cruzados'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='pais',
            field=models.CharField(blank=True, default='Argentina', max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='provincia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sabado_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sabado_turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('MT', 'Mañana/Tarde'), ('TN', 'Tarde/Noche'), ('FULL', 'Todo el Día'), ('NO', '❌ NO DISPONIBLE')], default='FULL', max_length=5),
        ),
        migrations.AddField(
            model_name='alumno',
            name='talle_remera',
            field=models.CharField(blank=True, max_length=10, verbose_name='Talle (Kit)'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tel. Emergencia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_trabajo',
            field=models.CharField(choices=[('SEDENTARIO', '🪑 Oficina/Sentado'), ('ACTIVO', '🚶 De pie/Movimiento'), ('MUY_ACTIVO', '🔨 Físico Pesado')], default='SEDENTARIO', max_length=20, verbose_name='Nivel Actividad Laboral'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='viernes_nota',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='alumno',
            name='viernes_turno',
            field=models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche'), ('MT', 'Mañana/Tarde'), ('TN', 'Tarde/Noche'), ('FULL', 'Todo el Día'), ('NO', '❌ NO DISPONIBLE')], default='FULL', max_length=5),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='ftp',
            field=models.IntegerField(default=200, help_text='FTP (Watts)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='itra_score',
            field=models.IntegerField(default=0, verbose_name='ITRA'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_trail_100k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ultra 100K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_trail_160k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Miler 160K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_trail_21k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Trail 21K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_trail_42k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Trail 42K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_trail_60k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ultra 60K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='prediccion_trail_80k',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ultra 80K'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='preferencia_alimentacion',
            field=models.CharField(choices=[('GELES', '⚡ Solo Geles'), ('REAL', '🍎 Comida Real'), ('MIX', '🔄 Mixto')], default='MIX', max_length=10, verbose_name='Pref. Nutrición'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='strava_athlete_id',
            field=models.CharField(blank=True, help_text='ID Strava', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='test_1k_tiempo',
            field=models.DurationField(blank=True, null=True, verbose_name='Test 1000m'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='test_5k_tiempo',
            field=models.DurationField(blank=True, null=True, verbose_name='Test 5k Llano'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='test_5k_trail_tiempo',
            field=models.DurationField(blank=True, null=True, verbose_name='Test 5k Cuesta'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='test_cooper_distancia',
            field=models.FloatField(default=0, verbose_name='Test Cooper (Km)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='vam_actual',
            field=models.FloatField(default=0, verbose_name='VAM (Calc)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='velocidad_pico',
            field=models.FloatField(default=0, verbose_name='Vpico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='velocidad_uae',
            field=models.FloatField(default=0, verbose_name='UAE'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='velocidad_uanae',
            field=models.FloatField(default=0, verbose_name='UANAE'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='vo2_max',
            field=models.FloatField(default=0, verbose_name='VO2 Máx (Calc)'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='desnivel_negativo_m',
            field=models.IntegerField(default=0, help_text='Metros D-'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='factor_terreno',
            field=models.FloatField(choices=[(1.0, '🛣️ Asfalto / Pista'), (1.05, '🌲 Sendero Corrible'), (1.15, '⛰️ Técnico Medio'), (1.25, '🧗 Técnico Duro'), (1.4, '🧟 Extremo')], default=1.05, help_text='Tecnicidad'),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='descripcion_detallada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='desnivel_planificado_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='feedback_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='intensidad_planificada',
            field=models.CharField(choices=[('Z1', 'Z1 Recup'), ('Z2', 'Z2 Base'), ('Z3', 'Z3 Tempo'), ('Z4', 'Z4 Umbral'), ('Z5', 'Z5 VO2')], default='Z2', max_length=50),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='rpe_planificado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='tipo_actividad',
            field=models.CharField(choices=[('RUN', 'Running (Calle)'), ('TRAIL', 'Trail Running (Montaña)'), ('CYCLING', 'Ciclismo / Ruta'), ('MTB', 'Ciclismo / MTB'), ('SWIMMING', 'Natación'), ('STRENGTH', 'Fuerza / Gimnasio'), ('CARDIO', 'Cardio / Funcional'), ('INDOOR_BIKE', 'Bici Fija / Rodillo'), ('REST', 'Descanso Total'), ('OTHER', 'Otro')], default='RUN', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='objetivo',
            field=models.CharField(choices=[('NONE', 'Sin Objetivo'), ('RPE_1', 'RPE 1'), ('RPE_2', 'RPE 2'), ('RPE_3', 'RPE 3'), ('RPE_4', 'RPE 4'), ('RPE_5', 'RPE 5'), ('RPE_6', 'RPE 6'), ('RPE_7', 'RPE 7'), ('RPE_8', 'RPE 8'), ('RPE_9', 'RPE 9'), ('RPE_10', 'RPE 10'), ('ZONA_FC', 'Zona FC'), ('PACE', 'Ritmo'), ('WATTS', 'Potencia')], default='RPE_2', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='tipo_duracion',
            field=models.CharField(choices=[('DISTANCE', 'Distancia'), ('TIME', 'Tiempo'), ('LAP_BUTTON', 'Lap'), ('CALORIES', 'Calorías'), ('OPEN', 'Abierto')], default='TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='unidad_duracion',
            field=models.CharField(choices=[('KM', 'Km'), ('METERS', 'm'), ('MILES', 'mi'), ('MIN', 'min'), ('SEC', 'seg'), ('HOURS', 'h'), ('N/A', '-')], default='MIN', max_length=10),
        ),
    ]
