# Generated by Django 5.2.8 on 2025-12-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_plantillaentrenamiento_options_alumno_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasoentrenamiento',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='alumno',
            name='certificado_medico',
            field=models.FileField(blank=True, null=True, upload_to='medicos/', verbose_name='📂 Certificado Médico (PDF/Img)'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='pasos_content/', verbose_name='📎 Adjunto'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='enlace_url',
            field=models.URLField(blank=True, null=True, verbose_name='🔗 Link Video/Web'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='objetivo_calculado_final',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='🎯 Objetivo Personalizado'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='objetivo_manual',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor Manual (Texto)'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='objetivo_rpe',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True, verbose_name='Valor RPE'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='objetivo_zona_vam',
            field=models.CharField(blank=True, choices=[('Z1', 'Z1 (<70%)'), ('Z2', 'Z2 (70-80%)'), ('Z3', 'Z3 (80-88%)'), ('Z4', 'Z4 (88-95%)'), ('Z5', 'Z5 (>95%)')], max_length=2, null=True, verbose_name='Valor Zona VAM'),
        ),
        migrations.AddField(
            model_name='pasoentrenamiento',
            name='tipo_objetivo',
            field=models.CharField(choices=[('RPE', '🧠 RPE (Escala 1-10)'), ('ZONA_VAM', '🏃\u200d♂️ Zona de Ritmo (% VAM)'), ('PACE_MANUAL', '⏱️ Ritmo Fijo Manual (Texto)'), ('NONE', '⚪ Sin Objetivo / Libre')], default='RPE', max_length=20, verbose_name='Tipo Objetivo'),
        ),
    ]
