# Generated by Django 5.2.8 on 2025-12-12 11:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_pasoentrenamiento_objetivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_ultimo_pago',
        ),
        migrations.AddField(
            model_name='alumno',
            name='esta_lesionado',
            field=models.BooleanField(default=False, verbose_name='🚑 ¿Está Lesionado?'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estado_actual',
            field=models.CharField(choices=[('ACTIVO', '✅ Activo (Entrenando)'), ('LESIONADO', '🚑 Inactivo (Lesión)'), ('PAUSA', '⏸️ Inactivo (Temporal/Vacaciones)'), ('DEUDA', '💰 Inactivo (Falta de Pago)'), ('BAJA', '❌ Baja Definitiva')], default='ACTIVO', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='valor_cuota_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Cuota ($)'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='certificado_medico',
            field=models.FileField(blank=True, null=True, upload_to='medicos/', verbose_name='📂 Certificado Médico'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='lesiones_alergias',
            field=models.TextField(blank=True, verbose_name='⚠️ Lesiones/Alergias (Detalle)'),
        ),
        migrations.AlterField(
            model_name='pasoentrenamiento',
            name='objetivo_calculado_final',
            field=models.CharField(blank=True, max_length=150, verbose_name='🎯 Objetivo Personalizado'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('TRANSFERENCIA', '🏦 Transferencia Bancaria'), ('EFECTIVO', '💵 Efectivo'), ('TARJETA', '💳 Tarjeta / Suscripción (Stripe/MP)'), ('BONIFICADO', '🎁 Becado / Canje')], default='TRANSFERENCIA', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/', verbose_name='🧾 Comprobante')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.alumno')),
            ],
            options={
                'verbose_name': '💰 Pago / Suscripción',
                'verbose_name_plural': '💰 Historial de Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
