# Generated by Django 5.2.8 on 2025-12-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_alumno_activo_remove_alumno_fecha_ultimo_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='ftp',
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True, verbose_name='📅 Último Pago'),
        ),
    ]
