# Generated by Django 5.2.8 on 2025-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_alumno_ftp_alumno_fecha_ultimo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='es_valido',
            field=models.BooleanField(default=False, verbose_name='✅ Validado por Entrenador'),
        ),
    ]
