# Generated by Django 5.2.8 on 2025-12-12 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pago_es_valido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Inicial Calle, Avanzado Montaña', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color_identificador', models.CharField(default='#F57C00', help_text='Color Hexadecimal para el calendario', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🏆 Equipo / Grupo',
                'verbose_name_plural': '🏆 Equipos',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='altura',
            field=models.FloatField(default=1.7, help_text='Altura en Metros'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='peso',
            field=models.FloatField(default=70.0, help_text='Peso en Kg'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.equipo'),
        ),
    ]
