# Generated by Django 5.2.8 on 2025-12-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_actividad_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Ej: Sentadilla Técnica', max_length=100)),
                ('archivo', models.FileField(help_text='Soporta MP4, MOV, GIF', upload_to='videos_ejercicios/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🎥 Video de Ejercicio',
                'verbose_name_plural': '🎥 Videos de Ejercicios',
            },
        ),
    ]
