# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations


def forwards(apps, schema_editor):
    Equipo = apps.get_model("core", "Equipo")
    Alumno = apps.get_model("core", "Alumno")

    # Backfill best-effort: si el equipo ya tiene alumnos, heredamos el entrenador del primer alumno.
    for equipo in Equipo.objects.filter(entrenador__isnull=True).iterator():
        alumno = (
            Alumno.objects.filter(equipo_id=equipo.id)
            .exclude(entrenador_id__isnull=True)
            .order_by("id")
            .first()
        )
        if alumno:
            equipo.entrenador_id = alumno.entrenador_id
            equipo.save(update_fields=["entrenador"])


def backwards(apps, schema_editor):
    # No revertimos automáticamente: podría borrar ownership legítimo.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_equipo_entrenador_videoejercicio_uploaded_by"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

