# Generated by Django 5.2.8 on 2025-12-17 04:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_backfill_equipo_entrenador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_activity_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('fetched', 'fetched'), ('saved', 'saved'), ('discarded', 'discarded'), ('failed', 'failed')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=160)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='StravaWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uid', models.CharField(db_index=True, max_length=80, unique=True)),
                ('object_type', models.CharField(db_index=True, max_length=40)),
                ('object_id', models.BigIntegerField(db_index=True)),
                ('aspect_type', models.CharField(db_index=True, max_length=20)),
                ('owner_id', models.BigIntegerField(db_index=True)),
                ('subscription_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payload_raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('received', 'received'), ('queued', 'queued'), ('processing', 'processing'), ('processed', 'processed'), ('ignored', 'ignored'), ('failed', 'failed')], db_index=True, default='received', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AddField(
            model_name='actividad',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.alumno'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='datos_brutos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='actividad',
            name='invalid_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='actividad',
            name='mapa_polilinea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='ritmo_promedio',
            field=models.FloatField(blank=True, help_text='Metros por segundo', null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='validity',
            field=models.CharField(choices=[('VALID', 'VALID'), ('DISCARDED', 'DISCARDED')], default='VALID', max_length=12),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='distancia',
            field=models.FloatField(default=0.0, help_text='Distancia en metros'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='strava_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_movimiento',
            field=models.IntegerField(default=0, help_text='Tiempo en segundos'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['usuario', '-fecha_inicio'], name='core_activi_usuario_1b5087_idx'),
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['alumno', '-fecha_inicio'], name='core_activi_alumno__8a2d1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrenamiento',
            constraint=models.UniqueConstraint(condition=models.Q(('strava_id__isnull', False), models.Q(('strava_id', ''), _negated=True)), fields=('strava_id',), name='uniq_entrenamiento_strava_id_not_blank'),
        ),
        migrations.AddField(
            model_name='stravaimportlog',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strava_import_logs', to='core.actividad'),
        ),
        migrations.AddField(
            model_name='stravaimportlog',
            name='alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strava_import_logs', to='core.alumno'),
        ),
        migrations.AddIndex(
            model_name='stravawebhookevent',
            index=models.Index(fields=['owner_id', '-received_at'], name='core_strava_owner_i_9d50cf_idx'),
        ),
        migrations.AddIndex(
            model_name='stravawebhookevent',
            index=models.Index(fields=['status', '-received_at'], name='core_strava_status_10b261_idx'),
        ),
        migrations.AddIndex(
            model_name='stravawebhookevent',
            index=models.Index(fields=['object_type', 'aspect_type', 'object_id'], name='core_strava_object__faf7d1_idx'),
        ),
        migrations.AddField(
            model_name='stravaimportlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='core.stravawebhookevent'),
        ),
        migrations.AddIndex(
            model_name='stravaimportlog',
            index=models.Index(fields=['strava_activity_id', '-created_at'], name='core_strava_strava__41c90d_idx'),
        ),
        migrations.AddIndex(
            model_name='stravaimportlog',
            index=models.Index(fields=['alumno', '-created_at'], name='core_strava_alumno__eaa126_idx'),
        ),
        migrations.AddIndex(
            model_name='stravaimportlog',
            index=models.Index(fields=['event', '-created_at'], name='core_strava_event_i_290c3b_idx'),
        ),
    ]
