# Generated by Django 5.2.8 on 2025-12-18 12:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_stravaimportlog_stravawebhookevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaActivitySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='strava', max_length=20)),
                ('athlete_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('strava_activity_id', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('succeeded', 'succeeded'), ('discarded', 'discarded'), ('failed', 'failed')], db_index=True, max_length=16)),
                ('locked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('locked_by_event_uid', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('discard_reason', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='discard_reason',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='event_time',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='last_duplicate_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='provider',
            field=models.CharField(db_index=True, default='strava', max_length=20),
        ),
        migrations.AddField(
            model_name='stravawebhookevent',
            name='provider_event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='stravawebhookevent',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('queued', 'queued'), ('processing', 'processing'), ('processed', 'processed'), ('discarded', 'discarded'), ('ignored', 'ignored'), ('failed', 'failed')], db_index=True, default='received', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stravawebhookevent',
            index=models.Index(fields=['provider', 'provider_event_id'], name='core_strava_provide_5eb3d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stravawebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_uid'), name='uniq_strava_provider_event_uid'),
        ),
        migrations.AddIndex(
            model_name='stravaactivitysyncstate',
            index=models.Index(fields=['athlete_id', '-updated_at'], name='core_strava_athlete_e09d81_idx'),
        ),
        migrations.AddIndex(
            model_name='stravaactivitysyncstate',
            index=models.Index(fields=['status', '-updated_at'], name='core_strava_status_a97aa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stravaactivitysyncstate',
            constraint=models.UniqueConstraint(fields=('provider', 'strava_activity_id'), name='uniq_strava_provider_activity_id'),
        ),
    ]
