# Generated by Django 5.2.8 on 2025-12-19

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def forwards_fill_source_fields(apps, schema_editor):
    Actividad = apps.get_model("core", "Actividad")
    # Backfill: source=strava; source_object_id=str(strava_id) si existe.
    qs = Actividad.objects.all().only("id", "strava_id", "source", "source_object_id")
    for act in qs.iterator():
        changed = False
        if not getattr(act, "source", None):
            act.source = "strava"
            changed = True
        if (not getattr(act, "source_object_id", "")) and getattr(act, "strava_id", None) is not None:
            act.source_object_id = str(act.strava_id)
            changed = True
        if changed:
            act.save(update_fields=["source", "source_object_id"])


def backwards_noop(apps, schema_editor):
    # No-op: mantenemos datos.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_strava_sync_hardening_phase4"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="source",
            field=models.CharField(
                choices=[
                    ("strava", "strava"),
                    ("garmin", "garmin"),
                    ("coros", "coros"),
                    ("suunto", "suunto"),
                    ("manual", "manual"),
                    ("other", "other"),
                ],
                db_index=True,
                default="strava",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="source_hash",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="actividad",
            name="source_object_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="strava_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="stravawebhookevent",
            name="actividad",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strava_webhook_events",
                to="core.actividad",
            ),
        ),
        migrations.RunPython(forwards_fill_source_fields, backwards_noop),
        migrations.AddConstraint(
            model_name="actividad",
            constraint=models.UniqueConstraint(
                condition=Q(("source_object_id__isnull", False), ~Q(("source_object_id", ""))),
                fields=("source", "source_object_id"),
                name="uniq_actividad_source_object_id_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="actividad",
            constraint=models.UniqueConstraint(
                condition=Q(("strava_id__isnull", False)),
                fields=("strava_id",),
                name="uniq_actividad_strava_id_not_null",
            ),
        ),
    ]

