# Generated by Django 5.2.8 on 2025-12-20

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_unify_actividad_multisource"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("strava", "strava")], db_index=True, max_length=20)),
                ("external_user_id", models.CharField(db_index=True, max_length=80)),
                ("status", models.CharField(choices=[("unlinked", "unlinked"), ("linked", "linked"), ("disabled", "disabled")], db_index=True, default="unlinked", max_length=20)),
                ("linked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_identities",
                        to="core.alumno",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "-updated_at"], name="core_externa_status_6d6b07_idx"),
                    models.Index(fields=["provider", "status", "-updated_at"], name="core_externa_provide_4f7e7f_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(fields=("provider", "external_user_id"), name="uniq_external_identity_provider_user"),
        ),
        migrations.AddConstraint(
            model_name="externalidentity",
            constraint=models.UniqueConstraint(
                condition=Q(("alumno__isnull", False)),
                fields=("provider", "alumno"),
                name="uniq_external_identity_provider_alumno_not_null",
            ),
        ),
        migrations.AlterField(
            model_name="stravawebhookevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "received"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("processed", "processed"),
                    ("link_required", "link_required"),
                    ("discarded", "discarded"),
                    ("ignored", "ignored"),
                    ("failed", "failed"),
                ],
                db_index=True,
                default="received",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stravaimportlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("fetched", "fetched"),
                    ("saved", "saved"),
                    ("deferred", "deferred"),
                    ("discarded", "discarded"),
                    ("failed", "failed"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stravaactivitysyncstate",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "running"),
                    ("succeeded", "succeeded"),
                    ("blocked", "blocked"),
                    ("discarded", "discarded"),
                    ("failed", "failed"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
    ]

