# Generated by Django 5.2.8 on 2025-12-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_external_identity_and_link_required'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalidentity',
            new_name='core_extern_status_c0182c_idx',
            old_name='core_externa_status_6d6b07_idx',
        ),
        migrations.RenameIndex(
            model_name='externalidentity',
            new_name='core_extern_provide_ba529f_idx',
            old_name='core_externa_provide_4f7e7f_idx',
        ),
    ]
