# Generated by Django 5.2.8 on 2025-12-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_core_externa_status_6d6b07_idx_core_extern_status_c0182c_idx_and_more'),
        ('core', '0045_athlete_sync_state'),
    ]

    operations = [
    ]
