# Generated by Django 5.2.8 on 2025-12-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_actividad_add_metrics_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='athletesyncstate',
            new_name='core_athlet_provide_61d9b0_idx',
            old_name='core_athletes_provider_5f224e_idx',
        ),
        migrations.RenameIndex(
            model_name='athletesyncstate',
            new_name='core_athlet_provide_bee1e8_idx',
            old_name='core_athletes_provider_1b04e3_idx',
        ),
        migrations.RenameIndex(
            model_name='externalidentity',
            new_name='core_extern_status_c0182c_idx',
            old_name='core_externa_status_6d6b07_idx',
        ),
        migrations.RenameIndex(
            model_name='externalidentity',
            new_name='core_extern_provide_ba529f_idx',
            old_name='core_externa_provide_4f7e7f_idx',
        ),
    ]
