# Generated by Django 5.2.8 on 2025-12-30 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_core_athletes_provider_5f224e_idx_core_athlet_provide_61d9b0_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaentrenamiento',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_entrenamiento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(help_text='Ej: Inicial Calle, Avanzado Montaña', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='alumno',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email', 'entrenador'), name='unique_alumno_email_per_coach'),
        ),
        migrations.AddConstraint(
            model_name='equipo',
            constraint=models.UniqueConstraint(fields=('nombre', 'entrenador'), name='unique_equipo_per_coach'),
        ),
    ]
