# Generated by Django 5.2.8 on 2025-12-30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0047_rename_core_athletes_provider_5f224e_idx_core_athlet_provide_61d9b0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipo",
            name="nombre",
            field=models.CharField(
                max_length=100,
                help_text="Ej: Inicial Calle, Avanzado Montaña",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipo",
            constraint=models.UniqueConstraint(
                fields=("nombre", "entrenador"),
                name="unique_team_per_coach",
            ),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="email",
            field=models.EmailField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="alumno",
            constraint=models.UniqueConstraint(
                fields=("email", "entrenador"),
                name="unique_student_email_per_coach",
            ),
        ),
        migrations.AddField(
            model_name="plantillaentrenamiento",
            name="entrenador",
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="plantillas_entrenamiento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

