# Generated by Django 5.2.8 on 2026-01-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_security_week1_constraints_and_tenant_fields'),
    ]

    operations = [
    ]
