# Generated by Django 5.2.8 on 2026-01-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_security_week1_constraints_and_tenant_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="entrenamiento",
            index=models.Index(fields=["alumno", "-fecha_asignada"], name="ent_alumno_fecha_desc"),
        ),
        migrations.AddIndex(
            model_name="entrenamiento",
            index=models.Index(fields=["alumno", "fecha_asignada"], name="ent_alumno_fecha"),
        ),
        migrations.AddIndex(
            model_name="entrenamiento",
            index=models.Index(fields=["fecha_asignada", "alumno"], name="ent_fecha_alumno"),
        ),
    ]

