# Generated by Django 5.2.8 on 2026-01-05 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_plantilla_versioning"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="entrenamiento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actividades_reconciliadas",
                to="core.entrenamiento",
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="actividad",
            name="reconciliation_method",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="actividad",
            name="reconciliation_score",
            field=models.FloatField(default=0),
        ),
    ]
