# Generated by Django 5.2.8 on 2026-01-05 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20260102_1615'),
        ('core', '0049_plantilla_versioning'),
    ]

    operations = [
    ]
