# Generated by Django 5.2.8 on 2026-01-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_actividad_entrenamiento_actividad_reconciled_at_and_more'),
        ('core', '0050_merge_20260105_1637'),
    ]

    operations = [
    ]
