# Generated by Django 5.2.8 on 2026-01-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_merge_20260105_1714"),
    ]

    operations = [
        migrations.AddField(
            model_name="stravawebhookevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="stravawebhookevent",
            index=models.Index(fields=["status", "updated_at"], name="core_strava_status_updated_at_idx"),
        ),
    ]
