# Generated by ChatGPT on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_strava_webhook_event_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="canonical_load",
            field=models.FloatField(
                blank=True,
                help_text="Carga canónica (PR6) derivada de TSS/TRIMP/RPE/relative_effort.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="canonical_load_method",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Método usado para la carga canónica (tss_power/tss_gap/trimp/rpe/relative_effort).",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="actividad",
            name="load_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Versión de la definición canónica de carga (ej: 1.0).",
                max_length=10,
            ),
        ),
    ]
