# Generated by Django 5.2.8 on 2026-01-15 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_actividad_add_elevation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stravawebhookevent',
            new_name='core_strava_status_2cb8d4_idx',
            old_name='core_strava_status_updated_at_idx',
        ),
    ]
