# Generated by Django 5.2.8 on 2026-02-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_rename_core_strava_status_updated_at_idx_core_strava_status_2cb8d4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthIntegrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('strava', 'Strava'), ('garmin', 'Garmin'), ('coros', 'Coros'), ('suunto', 'Suunto')], db_index=True, max_length=20)),
                ('connected', models.BooleanField(db_index=True, default=False)),
                ('athlete_id', models.CharField(blank=True, default='', help_text="Provider's athlete/user ID (e.g., Strava athlete_id)", max_length=120)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful activity sync from this provider', null=True)),
                ('error_reason', models.CharField(blank=True, db_index=True, default='', help_text='Machine-readable error code (e.g., missing_athlete_id, invalid_code)', max_length=60)),
                ('error_message', models.TextField(blank=True, default='', help_text='Human-readable error details (not exposed to frontend)')),
                ('last_error_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_integrations', to='core.alumno')),
            ],
            options={
                'verbose_name': 'OAuth Integration Status',
                'verbose_name_plural': 'OAuth Integration Statuses',
                'indexes': [models.Index(fields=['provider', 'connected'], name='core_oauthi_provide_3b4849_idx'), models.Index(fields=['alumno', '-updated_at'], name='core_oauthi_alumno__14c407_idx')],
                'constraints': [models.UniqueConstraint(fields=('alumno', 'provider'), name='uniq_oauth_integration_per_athlete_provider')],
            },
        ),
    ]
