# Generated by Django 5.2.8 on 2026-02-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_oauthintegrationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthintegrationstatus',
            name='status',
            field=models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('syncing', 'Syncing'), ('link_required', 'Link Required'), ('failed', 'Failed')], db_index=True, default='disconnected', max_length=20),
        ),
        migrations.AddIndex(
            model_name='oauthintegrationstatus',
            index=models.Index(fields=['provider', 'status'], name='core_oauthi_provide_948d46_idx'),
        ),
    ]
