# Generated by Django 5.2.8 on 2026-02-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_oauthintegrationstatus_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='estructura_schema_version',
            field=models.CharField(default='1.0', help_text='Versión del schema JSON', max_length=10),
        ),
    ]
