# Generated by Django 5.2.8 on 2026-02-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_entrenamiento_estructura_schema_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('external_user_id', models.CharField(db_index=True, max_length=120)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_credentials', to='core.alumno')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'alumno'], name='core_oauthc_provide_ec30c4_idx'), models.Index(fields=['provider', '-updated_at'], name='core_oauthc_provide_47279a_idx')],
                'constraints': [models.UniqueConstraint(fields=('alumno', 'provider'), name='uniq_oauth_credential_alumno_provider')],
            },
        ),
    ]
