# Generated by Django 5.2.8 on 2026-03-04 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_oauth_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('RUN', 'Running (Calle)'), ('TRAIL', 'Trail Running (Montaña)'), ('CYCLING', 'Ciclismo / Ruta'), ('MTB', 'Ciclismo / MTB'), ('SWIMMING', 'Natación'), ('STRENGTH', 'Fuerza / Gimnasio'), ('CARDIO', 'Cardio / Funcional'), ('INDOOR_BIKE', 'Bici Fija / Rodillo'), ('REST', 'Descanso Total'), ('OTHER', 'Otro')], db_index=True, help_text='Normalised sport type (TIPO_ACTIVIDAD).', max_length=50)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('duration_s', models.IntegerField(help_text='Elapsed duration in seconds.')),
                ('distance_m', models.FloatField(default=0.0, help_text='Distance in metres.')),
                ('elevation_gain_m', models.FloatField(blank=True, help_text='Cumulative elevation gain in metres. NULL = data not available.', null=True)),
                ('provider', models.CharField(choices=[('strava', 'Strava'), ('garmin', 'Garmin'), ('coros', 'Coros'), ('suunto', 'Suunto'), ('manual', 'Manual'), ('other', 'Other')], db_index=True, max_length=20)),
                ('provider_activity_id', models.CharField(db_index=True, help_text='Opaque ID assigned by the provider (e.g. Strava activity id).', max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Original provider payload kept for auditing and future re-processing.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alumno', models.ForeignKey(help_text='Athlete who performed the activity.', on_delete=django.db.models.deletion.CASCADE, related_name='completed_activities', to='core.alumno')),
                ('organization', models.ForeignKey(help_text='Coach / organisation that owns this activity record.', on_delete=django.db.models.deletion.CASCADE, related_name='completed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Completed Activity',
                'verbose_name_plural': 'Completed Activities',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['organization', '-start_time'], name='core_comple_organiz_68ec94_idx'), models.Index(fields=['alumno', '-start_time'], name='core_comple_alumno__b2f625_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'provider', 'provider_activity_id'), name='uniq_completed_activity_org_provider_id')],
            },
        ),
    ]
