# Generated by Django 5.2.8 on 2026-03-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_completedactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='source',
            field=models.CharField(choices=[('strava', 'strava'), ('garmin', 'garmin'), ('coros', 'coros'), ('suunto', 'suunto'), ('polar', 'polar'), ('wahoo', 'wahoo'), ('manual', 'manual'), ('other', 'other')], db_index=True, default='strava', max_length=20),
        ),
        migrations.AlterField(
            model_name='completedactivity',
            name='provider',
            field=models.CharField(choices=[('strava', 'Strava'), ('garmin', 'Garmin'), ('coros', 'Coros'), ('suunto', 'Suunto'), ('polar', 'Polar'), ('wahoo', 'Wahoo'), ('manual', 'Manual'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
