# Generated by Django 5.2.8 on 2026-03-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_membership_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('certifications', models.TextField(blank=True, default='')),
                ('specialties', models.CharField(blank=True, default='', max_length=300)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='core.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profiles', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(blank=True, help_text='Primary coach for this athlete within this organization. Nullable: an athlete may exist before a coach is assigned. Full multi-coach assignment patterns are handled by PR-104 AthleteCoachAssignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='core.coach')),
            ],
        ),
        migrations.AddIndex(
            model_name='coach',
            index=models.Index(fields=['organization', 'is_active'], name='core_coach_organiz_79b26a_idx'),
        ),
        migrations.AddConstraint(
            model_name='coach',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'organization'), name='uniq_active_coach_user_org'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['organization', 'team', 'is_active'], name='core_athlet_organiz_5953e3_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['organization', 'is_active'], name='core_athlet_organiz_065360_idx'),
        ),
        migrations.AddConstraint(
            model_name='athlete',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'organization'), name='uniq_active_athlete_user_org'),
        ),
    ]
