# Generated by Django 5.2.8 on 2026-03-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_coach_athlete_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteCoachAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('assistant', 'Assistant')], db_index=True, max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='core.athlete')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_assignments', to='core.coach')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_coach_assignments', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['athlete', 'organization', 'role'], name='core_athlet_athlete_2a2096_idx'), models.Index(fields=['coach', 'organization'], name='core_athlet_coach_i_f0c787_idx'), models.Index(fields=['organization', 'role'], name='core_athlet_organiz_ac05cf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True), ('role', 'primary')), fields=('athlete', 'organization'), name='uniq_active_primary_coach_per_athlete_org')],
            },
        ),
    ]
