# Generated by Django 5.2.8 on 2026-03-07 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_athlete_coach_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, help_text='Full birth date. Preferred over age field when available.', null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, help_text='Age in years. Used when birth_date is unknown.', null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, help_text='Body Mass Index. May be manually entered or computed.', null=True)),
                ('resting_hr_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hr_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vo2max', models.FloatField(blank=True, help_text='VO2max in ml/kg/min (lab or estimated).', null=True)),
                ('ftp_watts', models.PositiveSmallIntegerField(blank=True, help_text='Functional Threshold Power in watts (cycling).', null=True)),
                ('vam', models.FloatField(blank=True, help_text='Velocidad Ascensión Media in m/h (vertical climbing speed).', null=True)),
                ('lactate_threshold_pace_s_per_km', models.PositiveIntegerField(blank=True, help_text='Lactate threshold pace in seconds per km (running).', null=True)),
                ('running_economy', models.FloatField(blank=True, help_text='Running economy in ml O2/kg/km.', null=True)),
                ('training_age_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dominant_discipline', models.CharField(blank=True, choices=[('run', 'Running'), ('trail', 'Trail Running'), ('bike', 'Cycling'), ('swim', 'Swimming'), ('triathlon', 'Triathlon'), ('other', 'Other')], default='', max_length=20)),
                ('is_injured', models.BooleanField(db_index=True, default=False, help_text='Current injury flag. Affects training load recommendations.')),
                ('injury_notes', models.TextField(blank=True, default='')),
                ('hr_zones_json', models.JSONField(blank=True, default=dict, help_text='Heart rate zones as JSON. Structure: {z1: {min_bpm, max_bpm}, z2: ..., ...}. May be manually entered or auto-recalculated from max_hr_bpm.')),
                ('pace_zones_json', models.JSONField(blank=True, default=dict, help_text='Running pace zones as JSON. Structure: {z1: {min_s_km, max_s_km}, ...}. May be manually entered or auto-recalculated from lactate_threshold.')),
                ('power_zones_json', models.JSONField(blank=True, default=dict, help_text='Cycling power zones as JSON. Structure: {z1: {min_w, max_w}, ...}. May be manually entered or auto-recalculated from ftp_watts.')),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.athlete')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profiles', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_profile_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['organization'], name='core_athlet_organiz_018ee9_idx')],
            },
        ),
    ]
