# Generated by Django 5.2.8 on 2026-03-08 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_athlete_profile_goals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('discipline', models.CharField(choices=[('run', 'Running'), ('trail', 'Trail Running'), ('bike', 'Cycling'), ('swim', 'Swimming'), ('triathlon', 'Triathlon'), ('other', 'Other')], db_index=True, max_length=20)),
                ('event_date', models.DateField(db_index=True)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('elevation_gain_m', models.FloatField(blank=True, help_text='Total elevation gain in meters (relevant for trail/MTB events).', null=True)),
                ('event_url', models.URLField(blank=True, default='', help_text='Official event URL.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_events_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_events', to='core.organization')),
            ],
            options={
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['organization', 'event_date'], name='core_raceev_organiz_c80380_idx'), models.Index(fields=['organization', 'discipline', 'event_date'], name='core_raceev_organiz_b3c0ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name', 'event_date'), name='uniq_race_event_per_org_name_date')],
            },
        ),
    ]
