# Generated by Django 5.2.8 on 2026-03-08 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_race_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('priority', models.CharField(choices=[('A', 'A — Peak goal'), ('B', 'B — Secondary goal'), ('C', 'C — Developmental goal')], db_index=True, max_length=5)),
                ('goal_type', models.CharField(choices=[('finish', 'Finish')], default='finish', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('target_date', models.DateField(blank=True, db_index=True, help_text='Target date for personal goals not linked to a RaceEvent.', null=True)),
                ('coach_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='core.athlete')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_goals_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_goals', to='core.organization')),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_goals', to='core.raceevent')),
            ],
            options={
                'ordering': ['priority', 'target_date'],
                'indexes': [models.Index(fields=['organization', 'status'], name='core_athlet_organiz_f658ef_idx'), models.Index(fields=['athlete', 'status', 'priority'], name='core_athlet_athlete_a5c8ee_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('athlete', 'priority'), name='uniq_active_priority_per_athlete')],
            },
        ),
    ]
