# Generated by Django 5.2.8 on 2026-03-08 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_workout_library'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('discipline', models.CharField(choices=[('run', 'Running'), ('trail', 'Trail Running'), ('bike', 'Cycling'), ('swim', 'Swimming'), ('strength', 'Strength'), ('mobility', 'Mobility'), ('triathlon', 'Triathlon'), ('other', 'Other')], db_index=True, max_length=20)),
                ('session_type', models.CharField(choices=[('base', 'Base / Easy'), ('threshold', 'Threshold'), ('interval', 'Interval'), ('long', 'Long'), ('recovery', 'Recovery'), ('race_simulation', 'Race Simulation'), ('strength', 'Strength'), ('mobility', 'Mobility'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('estimated_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Coach-estimated total duration in seconds. Planning only.', null=True)),
                ('estimated_distance_meters', models.FloatField(blank=True, help_text='Coach-estimated total distance in meters. Planning only.', null=True)),
                ('structure_version', models.PositiveSmallIntegerField(default=1, help_text='Increments on material prescription changes. Never reset.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_workouts_created', to=settings.AUTH_USER_MODEL)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workouts', to='core.workoutlibrary')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workouts', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(help_text='Position of this block within the workout. Must be unique per workout.')),
                ('block_type', models.CharField(choices=[('warmup', 'Warm-Up'), ('main', 'Main Set'), ('cooldown', 'Cool-Down'), ('drill', 'Drill'), ('strength', 'Strength'), ('custom', 'Custom')], db_index=True, default='custom', max_length=20)),
                ('name', models.CharField(blank=True, default='', help_text='Optional label for display. Defaults to block_type if blank.', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='', help_text='Optional technique/demo video link for strength and drill blocks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_blocks', to='core.organization')),
                ('planned_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.plannedworkout')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(help_text='Position of this interval within the block. Must be unique per block.')),
                ('metric_type', models.CharField(choices=[('hr_zone', 'HR Zone'), ('pace', 'Pace'), ('power', 'Power'), ('rpe', 'RPE'), ('free', 'Free / Descriptive')], db_index=True, default='free', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable instruction. Always useful; required for FREE type.')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Interval duration in seconds.', null=True)),
                ('distance_meters', models.FloatField(blank=True, help_text='Interval distance in meters.', null=True)),
                ('target_value_low', models.FloatField(blank=True, help_text='Lower bound of intensity target. HR zone number / pace s/km min / power watts min / RPE low.', null=True)),
                ('target_value_high', models.FloatField(blank=True, help_text='Upper bound of intensity target.', null=True)),
                ('target_label', models.CharField(blank=True, default='', help_text='Human-readable intensity label, e.g. "Z2", "threshold", "10k pace".', max_length=100)),
                ('recovery_seconds', models.PositiveIntegerField(blank=True, help_text='Rest/recovery duration after each repetition, in seconds.', null=True)),
                ('recovery_distance_meters', models.FloatField(blank=True, help_text='Recovery distance (e.g. walk 200m) after each repetition.', null=True)),
                ('video_url', models.URLField(blank=True, default='', help_text='Optional demonstration video for strength or drill intervals.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='core.workoutblock')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_intervals', to='core.organization')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='plannedworkout',
            index=models.Index(fields=['organization', 'discipline', 'session_type'], name='core_planne_organiz_2b9abb_idx'),
        ),
        migrations.AddIndex(
            model_name='plannedworkout',
            index=models.Index(fields=['library'], name='core_planne_library_b62ef7_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutblock',
            constraint=models.UniqueConstraint(fields=('planned_workout', 'order_index'), name='uniq_block_order_per_workout'),
        ),
        migrations.AddConstraint(
            model_name='workoutinterval',
            constraint=models.UniqueConstraint(fields=('block', 'order_index'), name='uniq_interval_order_per_block'),
        ),
    ]
