# Generated by Django 5.2.8 on 2026-03-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_planned_workout_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(db_index=True, help_text='Original assignment date. Never modified after creation.')),
                ('athlete_moved_date', models.DateField(blank=True, db_index=True, help_text='If the athlete rescheduled, this records the new execution date. scheduled_date is never changed.', null=True)),
                ('day_order', models.PositiveSmallIntegerField(default=1, help_text='Order of this session within the day (1=first, 2=second, etc.).')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('moved', 'Moved'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('canceled', 'Canceled')], db_index=True, default='planned', max_length=20)),
                ('coach_notes', models.TextField(blank=True, default='', help_text='Coach instructions specific to this assignment. Not stored on template.')),
                ('athlete_notes', models.TextField(blank=True, default='', help_text='Athlete feedback/notes. Written only by the athlete.')),
                ('target_zone_override', models.CharField(blank=True, default='', help_text='e.g. "Z3" — overrides library template zone for this athlete.', max_length=100)),
                ('target_pace_override', models.CharField(blank=True, default='', help_text='e.g. "4:30/km" — overrides library template pace for this athlete.', max_length=100)),
                ('target_rpe_override', models.PositiveSmallIntegerField(blank=True, help_text='RPE 1–10 override for this assignment. Null = use template default.', null=True)),
                ('target_power_override', models.PositiveSmallIntegerField(blank=True, help_text='Power target in watts override. Null = use template default.', null=True)),
                ('snapshot_version', models.PositiveSmallIntegerField(default=1, help_text='Records the PlannedWorkout.structure_version at assignment time. Coaches can detect if the underlying template was updated after assignment.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='core.athlete')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_assignments', to='core.organization')),
                ('planned_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.plannedworkout')),
            ],
            options={
                'ordering': ['scheduled_date', 'day_order'],
                'indexes': [models.Index(fields=['athlete', 'scheduled_date', 'status'], name='core_workou_athlete_2beabf_idx'), models.Index(fields=['organization', 'scheduled_date'], name='core_workou_organiz_d2c799_idx'), models.Index(fields=['planned_workout'], name='core_workou_planned_dc0b68_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'scheduled_date', 'day_order'), name='uniq_assignment_athlete_date_order')],
            },
        ),
    ]
