# Generated by Django 5.2.8 on 2026-03-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_workout_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedactivity',
            name='athlete',
            field=models.ForeignKey(blank=True, help_text='Organization-first Athlete FK. Nullable for backward compatibility with rows ingested before PR-114. Backfill is a separate task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_activities_v2', to='core.athlete'),
        ),
        migrations.CreateModel(
            name='ActivityStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_type', models.CharField(choices=[('ingest', 'Ingest'), ('normalized', 'Normalized'), ('provider_update', 'Provider Update'), ('metric_snapshot', 'Metric Snapshot'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('provider', models.CharField(blank=True, default='', help_text="Provider slug (e.g. 'strava'). String, never a FK.", max_length=50)),
                ('payload', models.JSONField(help_text='Event payload. Structure is stream_type-dependent.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_streams', to='core.completedactivity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['completed_activity', 'stream_type'], name='core_activi_complet_377496_idx'), models.Index(fields=['completed_activity', '-created_at'], name='core_activi_complet_3dadf9_idx')],
            },
        ),
    ]
