# Generated by Django 5.2.8 on 2026-03-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_completed_activity_normalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedworkout',
            name='primary_target_variable',
            field=models.CharField(blank=True, choices=[('duration', 'Duration'), ('distance', 'Distance'), ('elevation_gain', 'Elevation Gain'), ('pace', 'Pace'), ('hr_zone', 'Heart Rate Zone (future)')], default='', help_text='Dominant target variable for Plan vs Real compliance scoring. If blank, the reconciliation engine auto-selects based on available estimated targets. Options: duration, distance, elevation_gain, pace, hr_zone.', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkoutReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled'), ('unmatched', 'Unmatched'), ('missed', 'Missed'), ('ambiguous', 'Ambiguous (Multiple Candidates)'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('match_method', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual (Coach Override)'), ('none', 'Not Matched')], default='none', help_text='How the activity was matched to the assignment.', max_length=10)),
                ('match_confidence', models.FloatField(blank=True, help_text='0..1. Confidence score from automatic matching.', null=True)),
                ('compliance_score', models.SmallIntegerField(blank=True, help_text='0..120. Null when no activity was matched.', null=True)),
                ('compliance_category', models.CharField(blank=True, default='', help_text='not_completed / regular / completed / over_completed.', max_length=20)),
                ('primary_target_used', models.CharField(blank=True, default='', help_text='Variable that drove the compliance score (duration / distance / pace / elevation_gain / hr_zone).', max_length=20)),
                ('score_detail', models.JSONField(blank=True, default=dict, help_text='Per-variable compliance breakdown. Schema: {variable: {planned, actual, ratio, score, signals}}. Populated when state=reconciled.')),
                ('signals', models.JSONField(blank=True, default=list, help_text='Structured reconciliation signals (ComplianceSignal constants). Examples: under_completed, duration_short, possible_overreaching.')),
                ('reconciled_at', models.DateTimeField(blank=True, help_text='Timestamp when reconciliation score was last computed.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='System diagnostic or coach notes. Extension point for future manual override workflow.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(help_text='The planned assignment being evaluated.', on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='core.workoutassignment')),
                ('completed_activity', models.ForeignKey(blank=True, help_text='The matched real activity. Null when state is missed, unmatched, pending, ambiguous, or error.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='core.completedactivity')),
                ('organization', models.ForeignKey(help_text='Tenant root. Always derived from assignment.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='workout_reconciliations', to='core.organization')),
            ],
            options={
                'verbose_name': 'Workout Reconciliation',
                'verbose_name_plural': 'Workout Reconciliations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'state'], name='core_workou_organiz_1ffa72_idx'), models.Index(fields=['organization', '-created_at'], name='core_workou_organiz_07d44a_idx'), models.Index(fields=['assignment'], name='core_workou_assignm_0b57c3_idx'), models.Index(fields=['completed_activity'], name='core_workou_complet_431a6f_idx')],
            },
        ),
    ]
