# Generated by Django 5.2.8 on 2026-03-11 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='entrenador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carreras_propias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
