# Generated by Django 5.2.8 on 2026-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_carrera_add_entrenador_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalidentity',
            name='provider',
            field=models.CharField(choices=[('strava', 'strava'), ('suunto', 'suunto')], db_index=True, max_length=20),
        ),
    ]
