# Generated by Django 5.2.8 on 2026-03-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_externalidentity_add_suunto'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutDeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('external_guide_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('snapshot_version', models.PositiveSmallIntegerField(default=1, help_text='PlannedWorkout.structure_version captured at push time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='core.workoutassignment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_delivery_records', to='core.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'provider', 'status'], name='core_workou_organiz_06055a_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'provider'), name='uniq_delivery_record_assignment_provider')],
            },
        ),
    ]
