# Generated by Django 5.2.8 on 2026-03-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_workoutinterval_add_repetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedworkout',
            name='planned_if',
            field=models.FloatField(blank=True, help_text='Planned Intensity Factor (0.0–1.5+). Ratio of planned NP/AP to athlete FTP. Planning only.', null=True),
        ),
        migrations.AddField(
            model_name='plannedworkout',
            name='planned_tss',
            field=models.FloatField(blank=True, help_text='Planned Training Stress Score. Coach-estimated TSS for the session. Planning only — never derived from execution data (Plan ≠ Real invariant).', null=True),
        ),
        migrations.CreateModel(
            name='AthleteZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_watts', models.FloatField(blank=True, help_text='Functional Threshold Power in watts.', null=True)),
                ('lthr_bpm', models.FloatField(blank=True, help_text='Lactate Threshold Heart Rate in beats per minute.', null=True)),
                ('threshold_pace_sec_per_km', models.FloatField(blank=True, help_text='Threshold running pace in seconds per kilometre.', null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update.')),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='core.athlete')),
            ],
            options={
                'indexes': [models.Index(fields=['athlete'], name='core_athlet_athlete_51abab_idx')],
            },
        ),
    ]
