# Generated by Django 5.2.8 on 2026-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0081_billing_organization_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan_tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], help_text='Tier de acceso que otorga este plan.', max_length=20)),
                ('price_ars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats_included', models.PositiveIntegerField(help_text='Atletas incluidos en el precio base.')),
                ('seats_extra_price_ars', models.DecimalField(decimal_places=2, default=0, help_text='Precio por atleta adicional sobre el límite incluido.', max_digits=10)),
                ('trial_days', models.PositiveIntegerField(default=15)),
                ('mp_plan_id', models.CharField(blank=True, help_text='ID del preapproval_plan en MercadoPago.', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'ordering': ['price_ars'],
            },
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='is_managed_plan',
            field=models.BooleanField(default=False, help_text='True = plan vendido directamente por el equipo Quantoryn (ej: Coach+IA). Omite checkout MP.'),
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, help_text='ID del preapproval en MercadoPago. Usado para correlacionar webhooks.', max_length=100, null=True),
        ),
    ]
