# Generated by Django 5.2.8 on 2026-03-22 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False


    dependencies = [
        ('core', '0082_mp_subscription_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Ej: 'Programa Presencial', 'Programa Online Elite'.", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price_ars', models.DecimalField(decimal_places=2, help_text='Precio mensual en ARS que el atleta paga al coach.', max_digits=10)),
                ('mp_plan_id', models.CharField(blank=True, help_text='ID del preapproval_plan en MercadoPago del coach.', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_pricing_plans', to='core.organization')),
            ],
            options={
                'verbose_name': 'Coach Pricing Plan',
                'ordering': ['organization', 'price_ars'],
            },
        ),
        migrations.CreateModel(
            name='AthleteSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('overdue', 'Moroso'), ('cancelled', 'Cancelado'), ('suspended', 'Suspendido')], default='pending', max_length=20)),
                ('mp_preapproval_id', models.CharField(blank=True, help_text='ID del preapproval en MercadoPago del atleta.', max_length=100, null=True)),
                ('last_payment_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_subscriptions', to='core.athlete')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_subscriptions', to='core.organization')),
                ('coach_plan', models.ForeignKey(help_text='PROTECT: no se puede borrar un plan con suscripciones activas.', on_delete=django.db.models.deletion.PROTECT, related_name='athlete_subscriptions', to='core.coachpricingplan')),
            ],
            options={
                'verbose_name': 'Athlete Subscription',
                'ordering': ['organization', 'status'],
            },
        ),
        migrations.AddConstraint(
            model_name='coachpricingplan',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_coach_plan_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='athletesubscription',
            constraint=models.UniqueConstraint(fields=('athlete', 'coach_plan'), name='unique_athlete_per_coach_plan'),
        ),
    ]
