# Generated by Django 5.2.8 on 2026-03-22 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_org_oauth_credential'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orgoauthcredential',
            new_name='core_orgoau_organiz_72a4f3_idx',
            old_name='core_orgoa_organiz_provider_idx',
        ),
    ]
