# Generated by Django 5.2.8 on 2026-03-22 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_rename_core_orgoa_organiz_provider_idx_core_orgoau_organiz_72a4f3_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('mp_preapproval_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('coach_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='core.coachpricingplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_invitations', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
