# Generated by Django 5.2.8 on 2026-03-23 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_athlete_device_preference_and_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='completedactivity',
            name='avg_hr',
            field=models.IntegerField(blank=True, help_text='Average heart rate in bpm. Populated by ingestion layer.', null=True),
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='avg_pace_s_km',
            field=models.FloatField(blank=True, help_text='Average pace in seconds/km (running). Populated by ingestion layer.', null=True),
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='avg_power_w',
            field=models.IntegerField(blank=True, help_text='Average power in watts (cycling). Populated by ingestion layer.', null=True),
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='canonical_load',
            field=models.FloatField(blank=True, help_text='Final TSS used for PMC. Computed by services_pmc.py.', null=True),
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='canonical_method',
            field=models.CharField(blank=True, default='', help_text='Method used to compute canonical_load: override / trimp / rtss_pace / estimated_duration', max_length=30),
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='max_hr',
            field=models.IntegerField(blank=True, help_text='Max heart rate in bpm. Populated by ingestion layer.', null=True),
        ),
        migrations.AddField(
            model_name='completedactivity',
            name='tss_override',
            field=models.FloatField(blank=True, help_text='Provider-supplied training load (Garmin Training Load, Polar TSS, etc.). If present, PMC uses this directly instead of TRIMP calculation.', null=True),
        ),
        migrations.CreateModel(
            name='ActivityLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tss', models.FloatField(help_text='Training Stress Score for this activity.')),
                ('method', models.CharField(help_text='override / trimp / rtss_pace / estimated_duration', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_loads', to=settings.AUTH_USER_MODEL)),
                ('completed_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_load', to='core.completedactivity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_loads', to='core.organization')),
            ],
            options={
                'verbose_name': 'Activity Load',
                'verbose_name_plural': 'Activity Loads',
                'indexes': [models.Index(fields=['organization', 'athlete', 'date'], name='core_activi_organiz_54cd47_idx')],
            },
        ),
        migrations.CreateModel(
            name='AthleteHRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_max', models.IntegerField(default=190, help_text='Max heart rate in bpm. Default: 190.')),
                ('hr_rest', models.IntegerField(default=55, help_text='Resting heart rate in bpm. Default: 55.')),
                ('threshold_pace_s_km', models.FloatField(blank=True, help_text='Anaerobic threshold pace in s/km (for rTSS fallback).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profiles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_hr_profiles', to='core.organization')),
            ],
            options={
                'verbose_name': 'Athlete HR Profile',
                'verbose_name_plural': 'Athlete HR Profiles',
                'unique_together': {('organization', 'athlete')},
            },
        ),
        migrations.CreateModel(
            name='DailyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tss', models.FloatField(default=0.0, help_text='Total TSS for the day (sum of all activities).')),
                ('ctl', models.FloatField(default=0.0, help_text='Chronic Training Load (42-day EWA). Fitness.')),
                ('atl', models.FloatField(default=0.0, help_text='Acute Training Load (7-day EWA). Fatigue.')),
                ('tsb', models.FloatField(default=0.0, help_text='Training Stress Balance (CTL - ATL). Form/Freshness.')),
                ('ars', models.IntegerField(default=50, help_text='Athlete Readiness Score 0-100 derived from TSB zone.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_loads', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_loads', to='core.organization')),
            ],
            options={
                'verbose_name': 'Daily Load',
                'verbose_name_plural': 'Daily Loads',
                'indexes': [models.Index(fields=['organization', 'athlete', '-date'], name='core_dailyl_organiz_f5bfca_idx')],
                'unique_together': {('organization', 'athlete', 'date')},
            },
        ),
    ]
