# Generated by Django 5.2.8 on 2026-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_plannedworkout_difficulty_elevation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutblock',
            name='block_type',
            field=models.CharField(choices=[('warmup', 'Warm-Up'), ('main', 'Main Set'), ('cooldown', 'Cool-Down'), ('drill', 'Drill'), ('strength', 'Strength'), ('custom', 'Custom'), ('recovery_step', 'Recuperación'), ('free', 'Libre')], db_index=True, default='custom', max_length=20),
        ),
    ]
