# Generated by Django 5.2.8 on 2026-03-26 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_workoutblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='location_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='athlete',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='actual_distance_meters',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='actual_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='actual_elevation_gain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='compliance_color',
            field=models.CharField(blank=True, choices=[('green', 'green'), ('yellow', 'yellow'), ('red', 'red'), ('blue', 'blue'), ('gray', 'gray')], default='gray', help_text='Smart compliance category computed on save when status=completed.', max_length=10),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='rpe',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rate of Perceived Exertion 1–5 (athlete self-report).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='weather_snapshot',
            field=models.JSONField(blank=True, help_text='OWM forecast snapshot for the scheduled date (enriched on list).', null=True),
        ),
    ]
