# Generated by Django 5.2.8 on 2026-03-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_pr145d_compliance_rpe_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedworkout',
            name='is_assignment_snapshot',
            field=models.BooleanField(default=False, help_text='True when this PlannedWorkout was cloned for a specific WorkoutAssignment. Snapshots are excluded from library listings.'),
        ),
        migrations.AlterField(
            model_name='plannedworkout',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_workouts', to='core.workoutlibrary'),
        ),
    ]
