# Generated by Django 5.2.8 on 2026-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_pr145f_workout_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutassignment',
            name='coach_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workoutassignment',
            name='coach_commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
