# Generated by Django 5.2.8 on 2026-03-27 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_pr145g_coach_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_teams', to=settings.AUTH_USER_MODEL, verbose_name='Atletas del grupo'),
        ),
    ]
