# Generated by Django 5.2.8 on 2026-03-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_pr147b_message_session_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='best_10k_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Personal best 10K time in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='best_21k_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Personal best 21K (half marathon) time in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='best_42k_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Personal best 42K (marathon) time in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='clothing_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='menstrual_cycle_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Average menstrual cycle length in days.', null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='menstrual_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='pace_1000m_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Best 1000m series pace in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='preferred_training_time',
            field=models.CharField(blank=True, choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('evening', 'Noche')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='weekly_available_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Weekly hours available for training.', null=True),
        ),
        migrations.CreateModel(
            name='AthleteAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', help_text="Reason for unavailability (e.g. 'Trabajo', 'Estudios').", max_length=100)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('evening', 'Noche')], default='', max_length=20)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='core.athlete')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_availabilities', to='core.organization')),
            ],
            options={
                'ordering': ['day_of_week'],
                'indexes': [models.Index(fields=['organization', 'athlete'], name='core_athlet_organiz_ebccc3_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'organization', 'day_of_week'), name='uniq_athlete_availability_day')],
            },
        ),
    ]
