# Generated by Django 5.2.8 on 2026-03-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_athleteprofile_best_10k_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinvitation',
            name='coach_plan',
            field=models.ForeignKey(blank=True, help_text='If null, athlete selects plan during onboarding.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='core.coachpricingplan'),
        ),
    ]
