# Generated by Django 5.2.8 on 2026-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_organizationinvitelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesubscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='End of 7-day trial period. After this, athlete must pay to access content.', null=True),
        ),
    ]
