# Generated by Django 5.2.8 on 2026-03-31 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_athletesubscription_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='last_period_date',
            field=models.DateField(blank=True, help_text='Start date of the last menstrual period. Used to calculate current phase.', null=True),
        ),
        migrations.CreateModel(
            name='AthleteInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_type', models.CharField(choices=[('muscular', 'Muscular'), ('articular', 'Articular'), ('tendinosa', 'Tendinosa'), ('ligamentosa', 'Ligamentosa'), ('osea', 'Ósea'), ('otra', 'Otra')], max_length=20)),
                ('body_zone', models.CharField(choices=[('cabeza', 'Cabeza'), ('cuello', 'Cuello'), ('hombro', 'Hombro'), ('brazo', 'Brazo'), ('codo', 'Codo'), ('muneca', 'Muñeca'), ('mano', 'Mano'), ('pecho', 'Pecho'), ('espalda_alta', 'Espalda alta'), ('espalda_baja', 'Espalda baja'), ('cadera', 'Cadera'), ('muslo', 'Muslo'), ('rodilla', 'Rodilla'), ('pantorrilla', 'Pantorrilla'), ('tobillo', 'Tobillo'), ('pie', 'Pie')], max_length=20)),
                ('side', models.CharField(choices=[('izquierdo', 'Izquierdo'), ('derecho', 'Derecho'), ('ambos', 'Ambos'), ('central', 'Central')], default='central', max_length=20)),
                ('severity', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('severa', 'Severa')], default='leve', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('date_occurred', models.DateField()),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('en_recuperacion', 'En recuperación'), ('resuelta', 'Resuelta')], default='activa', max_length=20)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='core.athlete')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_injuries', to='core.organization')),
            ],
            options={
                'ordering': ['-date_occurred'],
                'indexes': [models.Index(fields=['organization', 'athlete', 'status'], name='core_athlet_organiz_3f30bc_idx')],
            },
        ),
    ]
