# Generated by Django 5.2.8 on 2026-04-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_wellnesscheckin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='wellnesscheckin',
            new_name='core_wellne_organiz_60f677_idx',
            old_name='core_wellne_organiz_idx',
        ),
        migrations.AlterField(
            model_name='athleteinjury',
            name='body_zone',
            field=models.CharField(choices=[('cabeza', 'Cabeza'), ('cuello', 'Cuello'), ('hombro', 'Hombro'), ('brazo', 'Brazo'), ('codo', 'Codo'), ('muneca', 'Muñeca'), ('mano', 'Mano'), ('pecho', 'Pecho'), ('espalda_alta', 'Espalda alta'), ('espalda_baja', 'Espalda baja'), ('cadera', 'Cadera'), ('muslo', 'Muslo'), ('rodilla', 'Rodilla'), ('pantorrilla', 'Pantorrilla'), ('espinilla', 'Espinilla'), ('tobillo', 'Tobillo'), ('pie', 'Pie'), ('gluteo', 'Glúteo'), ('isquiotibial', 'Isquiotibial'), ('talon', 'Talón'), ('planta_del_pie', 'Planta del pie')], max_length=20),
        ),
    ]
