# Generated by Django 5.2.8 on 2026-04-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_athleteinjury_bodyzones_backside'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletegoal',
            name='target_distance_km',
            field=models.FloatField(blank=True, help_text='Target race distance in kilometers.', null=True),
        ),
        migrations.AddField(
            model_name='athletegoal',
            name='target_elevation_gain_m',
            field=models.IntegerField(blank=True, help_text='Target elevation gain in meters (trail/MTB goals).', null=True),
        ),
    ]
