# Generated by Django 5.2.8 on 2026-04-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_athletegoal_distance_elevation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, help_text='Monday of the target week.')),
                ('phase', models.CharField(choices=[('carga', 'Carga'), ('descarga', 'Descarga'), ('carrera', 'Carrera'), ('descanso', 'Descanso'), ('lesion', 'Lesión')], db_index=True, max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_weeks', to='core.athlete')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_weeks', to='core.organization')),
            ],
            options={
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['organization', 'week_start'], name='core_traini_organiz_bed10d_idx')],
                'constraints': [models.UniqueConstraint(fields=('athlete', 'week_start'), name='unique_training_week_athlete_week')],
            },
        ),
    ]
