# Generated by Django 5.2.8 on 2026-04-02 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_pr155_trainingweek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('period_days', models.IntegerField(default=90)),
                ('coach_message', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('athlete_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_reports', to=settings.AUTH_USER_MODEL)),
                ('coach_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_reports', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_reports', to='core.organization')),
            ],
            options={
                'verbose_name': 'Athlete Report',
                'verbose_name_plural': 'Athlete Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
