# Generated by Django 5.2.8 on 2026-04-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_org_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='coach',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='membership',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='membership',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
