# Generated by Django 5.2.8 on 2026-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_athletesubscription_mp_payer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesubscription',
            name='cancellation_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesubscription',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athletesubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesubscription',
            name='pause_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletesubscription',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='athletesubscription',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athletesubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('overdue', 'Moroso'), ('paused', 'Pausado'), ('cancelled', 'Cancelado'), ('suspended', 'Suspendido')], default='pending', max_length=20),
        ),
    ]
