# Generated by Django 5.2.8 on 2026-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_pr167c_subscription_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletesubscription',
            name='last_pre_charge_notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time a pre-charge reminder was sent for this subscription.', null=True),
        ),
    ]
