# Generated by Django 5.2.8 on 2026-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_pr169_pre_charge_notification_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedactivity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='completedactivity',
            index=models.Index(fields=['organization', 'deleted_at', '-start_time'], name='core_comple_organiz_2c9c39_idx'),
        ),
        migrations.AddIndex(
            model_name='stravawebhookevent',
            index=models.Index(fields=['owner_id', 'status'], name='core_strava_owner_i_760c43_idx'),
        ),
    ]
