# Generated by Django 5.2.8 on 2026-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_pr185_completed_activity_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthintegrationstatus',
            name='last_rescue_dispatched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
