# Generated by Django 5.2.8 on 2026-04-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_pr185_oauth_rescue_throttle'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
