"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
from datetime import timedelta # Importamos timedelta para JWT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Detectar tests (y permitir fallback local si Postgres no está configurado).
RUNNING_TESTS = "test" in sys.argv

# --- CARGA DE VARIABLES DE ENTORNO ---
env_path = BASE_DIR / '.env'
load_dotenv(env_path)

# --- VALIDACIÓN ESTRICTA DE CONFIGURACIÓN ---
def get_env_variable(var_name, default=None, required=True):
    try:
        return os.environ[var_name]
    except KeyError:
        if required:
            error_msg = f"❌ ERROR CRÍTICO: La variable de entorno {var_name} no está configurada."
            print(error_msg)
            if not default:
                raise Exception(error_msg)
        return default

# Variables Críticas
SECRET_KEY = get_env_variable("SECRET_KEY", default="test-secret-key", required=not RUNNING_TESTS)
DEBUG = get_env_variable("DEBUG", default=("True" if RUNNING_TESTS else "False"), required=not RUNNING_TESTS) == "True"

# --- CONFIGURACIÓN DE HOSTS (Ngrok Ready) ---
if DEBUG:
    # Permitimos todo en desarrollo para evitar problemas con túneles dinámicos
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = get_env_variable("ALLOWED_HOSTS", "localhost").split(",")

# Strava (opcional en local/tests, requerido solo si querés en prod)
STRAVA_CLIENT_ID = get_env_variable("STRAVA_CLIENT_ID", default="", required=(not DEBUG and not RUNNING_TESTS))
STRAVA_CLIENT_SECRET = get_env_variable("STRAVA_CLIENT_SECRET", default="", required=(not DEBUG and not RUNNING_TESTS))
# Este es el token que definiste en tu .env (MENDIETA_SECRET_TOKEN_2025)
STRAVA_WEBHOOK_VERIFY_TOKEN = get_env_variable("STRAVA_WEBHOOK_VERIFY_TOKEN", default="", required=(not DEBUG and not RUNNING_TESTS))

# OpenAI (opcional en local)
OPENAI_API_KEY = get_env_variable("OPENAI_API_KEY", default="", required=False)


# ==============================================================================
#  APLICACIONES INSTALADAS
# ==============================================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # <--- REQUERIDO POR ALLAUTH

    # --- TERCEROS ---
    'nested_admin',
    'rest_framework',
    'rest_framework_simplejwt', # <--- NUEVO: JWT
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',           # <--- FILTROS AVANZADOS API
    'drf_yasg',
    'corsheaders', 
    
    # --- LOGIN SOCIAL (ALLAUTH) ---
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.strava', 

    # --- MIS APPS ---
    'core',
    'analytics',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <--- CORS SIEMPRE PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Multi-tenant context (tenant = coach_id). No bloquea, solo expone request.tenant_coach_id.
    'core.middleware.TenantContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', # ALLAUTH AL FINAL
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core/templates'], # <--- IMPORTANTE PARA EL DASHBOARD
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request', # Requerido por Allauth
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ==============================================================================
#  BASE DE DATOS
# ==============================================================================
DATABASES = {
    # Importante:
    # - Si DB_NAME/DB_USER/DB_PASSWORD están configuradas, SIEMPRE usamos Postgres (también en migrate/showmigrations).
    # - Si NO están configuradas (CI/entornos sin .env), caemos a SQLite para permitir comandos básicos.
    "default": (
        {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:" if RUNNING_TESTS else str(BASE_DIR / "db.sqlite3"),
        }
        if not all(os.environ.get(k) for k in ("DB_NAME", "DB_USER", "DB_PASSWORD"))
        else {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": get_env_variable("DB_NAME"),
            "USER": get_env_variable("DB_USER"),
            "PASSWORD": get_env_variable("DB_PASSWORD"),
            "HOST": get_env_variable("DB_HOST", "localhost", required=False),
            "PORT": get_env_variable("DB_PORT", "5432", required=False),
        }
    ),
}


# ==============================================================================
#  SEGURIDAD Y PASSWORD
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================================================
#  ARCHIVOS ESTÁTICOS Y MULTIMEDIA (VIDEOS & DOCUMENTOS)
# ==============================================================================

# Archivos CSS/JS del sistema (Admin)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Archivos subidos por el usuario (Videos de Gym, Comprobantes)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- 🚀 ESCALABILIDAD: LÍMITES DE SUBIDA (VIDEOS) ---
# Aumentamos el límite para permitir videos cortos de técnica (Gym Pro)
# Default Django es 2.5MB. Lo subimos a 100MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
#  REST FRAMEWORK & SEGURIDAD (JWT)
# ==============================================================================
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {'type': 'apiKey', 'name': 'Authorization', 'in': 'header'}
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        #'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # 🔒 CERRADO POR DEFECTO
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

    # ✅ FASE 4: throttling global
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '300/min',
        'login': '5/min',      # para /api/token/
        'refresh': '20/min',   # para /api/token/refresh/
    },
}

# --- CONFIGURACIÓN JWT (Simple JWT) ---
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),    # Refresh dura 7 días
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    
    # ✅ Recomendado
    'UPDATE_LAST_LOGIN': True,
}

# ==============================================================================
#  CELERY / REDIS (CONFIGURACIÓN OPTIMIZADA)
# ==============================================================================
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# --- MODO INMEDIATO (EAGER MODE) ---
# CRÍTICO: Esto hace que Django ejecute la tarea inmediatamente en local
# sin esperar a un worker externo. Vital para ver los logs en tiempo real.
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_EAGER_PROPAGATES = False

# ==============================================================================
#  EMAIL (DESARROLLO)
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'Mendieta Platform <noreply@mendieta.ai>'

# ==============================================================================
#  CORS & SEGURIDAD WEBHOOKS
# ==============================================================================
# Permitir acceso desde el Frontend (React)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True # 🔓 Desarrollo fácil
else:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "http://localhost:3000",
    ]

# CRÍTICO: Dominios confiables para recibir POST (Webhooks Strava)
# IMPORTANTE: Asegúrate de que esta URL coincida con la de tu Ngrok actual
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://overfaithfully-piquant-bryn.ngrok-free.dev", 
]

# ==============================================================================
#  CONFIGURACIÓN MAESTRA DE STRAVA (ALLAUTH)
# ==============================================================================

SITE_ID = 1 

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# --- REDIRECCIONES ---
LOGIN_REDIRECT_URL = 'http://localhost:5173/dashboard'
LOGOUT_REDIRECT_URL = 'http://localhost:5173/'
ACCOUNT_CONNECT_REDIRECT_URL = 'http://localhost:5173/dashboard'

# --- COMPORTAMIENTO SOCIAL ---
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_STORE_TOKENS = True 
ACCOUNT_SESSION_REMEMBER = True 
ACCOUNT_LOGOUT_ON_GET = True

# --- RELAJAR REGLAS DE EMAIL ---
ACCOUNT_EMAIL_VERIFICATION = 'none' 
ACCOUNT_SIGNUP_FIELDS = ['email', 'username']

SOCIALACCOUNT_PROVIDERS = {
    'strava': {
        'SCOPE': [
            'read,activity:read_all,profile:read_all'
        ],
        'AUTH_PARAMS': {
            'approval_prompt': 'force',
        },
        'verified_email': False,
    }
}