"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CARGA DE VARIABLES DE ENTORNO ---
env_path = BASE_DIR / '.env'
load_dotenv(env_path)

# --- VALIDACIÓN ESTRICTA DE CONFIGURACIÓN (Production-Grade) ---
def get_env_variable(var_name, default=None, required=True):
    try:
        return os.environ[var_name]
    except KeyError:
        if required:
            error_msg = f"❌ ERROR CRÍTICO: La variable de entorno {var_name} no está configurada."
            print(error_msg)
            # En producción, esto debería detener el deploy.
            # En desarrollo, lanzamos una excepción clara.
            raise Exception(error_msg)
        return default

# Variables Críticas (Sin esto, la app no debe arrancar)
SECRET_KEY = get_env_variable("SECRET_KEY")
DEBUG = get_env_variable("DEBUG", "False") == "True"

# Configuración de Hosts (Segura)
if DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    # En producción, aquí iría tu dominio real (ej: 'plataforma.mendieta.com')
    ALLOWED_HOSTS = get_env_variable("ALLOWED_HOSTS", "localhost").split(",")

# Credenciales de Terceros (Strava)
STRAVA_CLIENT_ID = get_env_variable("STRAVA_CLIENT_ID")
STRAVA_CLIENT_SECRET = get_env_variable("STRAVA_CLIENT_SECRET")

# ---------------------------------------------------------------

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # <--- REQUERIDO

    # --- TERCEROS ---
    'nested_admin',
    'rest_framework',
    'drf_yasg',
    
    # --- LOGIN SOCIAL (ALLAUTH) ---
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.strava', # <--- Proveedor Strava

    # --- MIS APPS ---
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # IMPORTANTE: Esta línea es necesaria para las versiones modernas de allauth
    'allauth.account.middleware.AccountMiddleware', 
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # --- REQUERIDO POR ALLAUTH ---
                'django.template.context_processors.request', 
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'mendieta_db',
        'USER': 'postgres',
        'PASSWORD': 'Menfer95',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- SWAGGER ---
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey', 'name': 'Authorization', 'in': 'header'
        }
    }
}

# --- REST FRAMEWORK ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# --- CELERY / REDIS ---
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# ==========================================
# 🔗 CONFIGURACIÓN DE STRAVA (ALLAUTH)
# ==========================================

SITE_ID = 1 

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# --- REDIRECCIONES ---
# Login normal
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/dashboard/'
# NUEVO: Redirección tras conectar una cuenta social (evita la pantalla blanca)
ACCOUNT_CONNECT_REDIRECT_URL = '/dashboard/'

# --- COMPORTAMIENTO SOCIAL ---
# Login inmediato, saltando confirmaciones innecesarias
SOCIALACCOUNT_LOGIN_ON_GET = True

# NUEVO: Forzar guardado del Token (CRUCIAL para leer actividades después en Background)
SOCIALACCOUNT_STORE_TOKENS = True

SOCIALACCOUNT_PROVIDERS = {
    'strava': {
        'APP': {
            'client_id': STRAVA_CLIENT_ID,
            'secret': STRAVA_CLIENT_SECRET,
            'key': ''
        },
        # ------------------------------------------------------------------
        # SOLUCIÓN DE INGENIERÍA:
        # Inyectamos 'scope' como string en AUTH_PARAMS.
        # ------------------------------------------------------------------
        'AUTH_PARAMS': {
            'scope': 'read,activity:read_all,profile:read_all', 
            'approval_prompt': 'force', 
        },
        'VERIFIED_EMAIL': True,
        'VERSION': 'v3',
    }
}