# Generated by Django 5.2.8 on 2025-12-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_entrenamiento_distancia_planificada_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialFitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tss_diario', models.FloatField(default=0, help_text='Suma de TSS de todos los entrenamientos del día')),
                ('ctl', models.FloatField(default=0, help_text='Fitness (Carga Crónica)')),
                ('atl', models.FloatField(default=0, help_text='Fatiga (Carga Aguda)')),
                ('tsb', models.FloatField(default=0, help_text='Forma (Equilibrio)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_fitness', to='core.alumno')),
            ],
            options={
                'verbose_name': '📈 Historial de Fitness',
                'verbose_name_plural': '📈 Historial de Fitness',
                'ordering': ['-fecha'],
                'unique_together': {('alumno', 'fecha')},
            },
        ),
    ]
