# Generated by Django 5.2.8 on 2025-12-06 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0016_entrenamiento_carbohidratos_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaRendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('FTP_UP', '📈 Posible Aumento de FTP'), ('HR_MAX', '❤️ Nueva FC Máxima')], max_length=50)),
                ('valor_detectado', models.FloatField()),
                ('valor_anterior', models.FloatField()),
                ('mensaje', models.TextField()),
                ('visto_por_coach', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno')),
            ],
        ),
    ]
