# Generated by Django 5.2.8 on 2025-12-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_injuryrisksnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='injuryrisksnapshot',
            new_name='analytics_i_entrena_93174d_idx',
            old_name='analytics_in_entrena_60a63c_idx',
        ),
        migrations.RenameIndex(
            model_name='injuryrisksnapshot',
            new_name='analytics_i_alumno__36f0b5_idx',
            old_name='analytics_in_alumno__e56a57_idx',
        ),
    ]
