# Generated by Django 5.2.8 on 2025-12-17 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_rename_analytics_in_entrena_60a63c_idx_analytics_i_entrena_93174d_idx_and_more'),
        ('core', '0039_stravaimportlog_stravawebhookevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('overtraining_risk', 'overtraining_risk'), ('low_compliance', 'low_compliance'), ('anomaly', 'anomaly')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], db_index=True, default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], db_index=True, default='open', max_length=10)),
                ('message', models.TextField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.alumno')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.equipo')),
            ],
            options={
                'indexes': [models.Index(fields=['entrenador', 'status', '-created_at'], name='analytics_a_entrena_879c6c_idx'), models.Index(fields=['alumno', 'status', '-created_at'], name='analytics_a_alumno__b588ec_idx'), models.Index(fields=['type', 'status', '-created_at'], name='analytics_a_type_8efe29_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('alumno', 'type'), name='uniq_open_alert_per_type_alumno')],
            },
        ),
        migrations.CreateModel(
            name='SessionComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('compliance_score', models.PositiveSmallIntegerField(default=0, help_text='0–100')),
                ('classification', models.CharField(choices=[('on_track', 'on_track'), ('under', 'under'), ('over', 'over'), ('anomaly', 'anomaly')], db_index=True, max_length=20)),
                ('explanation', models.TextField(blank=True, default='')),
                ('next_action', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to='core.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_comparisons', to='core.alumno')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_comparisons', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_comparisons', to='core.equipo')),
                ('planned_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparisons', to='core.entrenamiento')),
            ],
            options={
                'indexes': [models.Index(fields=['entrenador', '-fecha'], name='analytics_s_entrena_f93070_idx'), models.Index(fields=['alumno', '-fecha'], name='analytics_s_alumno__89a92e_idx'), models.Index(fields=['classification', '-created_at'], name='analytics_s_classif_a0dc05_idx')],
            },
        ),
    ]
