# Generated by Django 5.2.8 on 2025-12-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_alert_sessioncomparison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertarendimiento",
            name="fecha",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="alertarendimiento",
            index=models.Index(fields=["alumno", "-fecha", "-id"], name="analytics_al_alumno__06bb9c_idx"),
        ),
    ]
