# Generated by Django 5.2.8 on 2025-12-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alertarendimiento_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertarendimiento',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.RenameIndex(
            model_name='alertarendimiento',
            new_name='analytics_a_alumno__a9cfef_idx',
            old_name='analytics_al_alumno__06bb9c_idx',
        ),
    ]
