# Generated by Django 5.2.8 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_alter_alertarendimiento_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialfitness",
            name="distance_m",
            field=models.FloatField(default=0, help_text="Distancia total del día (m)"),
        ),
        migrations.AddField(
            model_name="historialfitness",
            name="moving_time_s",
            field=models.IntegerField(default=0, help_text="Tiempo total en movimiento del día (s)"),
        ),
    ]

