# Generated by Django 5.2.8 on 2025-12-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alert_actionable_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyactivityagg',
            new_name='analytics_d_alumno__e7515b_idx',
            old_name='analytics_d_alumno__f014ff_idx',
        ),
        migrations.RenameIndex(
            model_name='pmchistory',
            new_name='analytics_p_alumno__2f2c72_idx',
            old_name='analytics_p_alumno__a0b5c7_idx',
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('critical', 'critical'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], db_index=True, default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('injury_risk_up_and_fatigue_high', 'injury_risk_up_and_fatigue_high'), ('compliance_drop_week', 'compliance_drop_week'), ('acute_load_spike', 'acute_load_spike'), ('form_too_negative_sustained', 'form_too_negative_sustained'), ('missed_sessions_vs_plan', 'missed_sessions_vs_plan'), ('overtraining_risk', 'overtraining_risk'), ('low_compliance', 'low_compliance'), ('anomaly', 'anomaly')], db_index=True, max_length=40),
        ),
    ]
