# Generated by Django 5.2.8 on 2026-01-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_rename_analytics_d_alumno__f014ff_idx_analytics_d_alumno__e7515b_idx_and_more'),
    ]

    operations = [
    ]
