# Generated by Django 5.2.8 on 2026-01-12 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0011_auto_20260102_1615"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsRangeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_type",
                    models.CharField(
                        choices=[("PMC", "PMC"), ("WEEK_SUMMARY", "WEEK_SUMMARY")],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "sport",
                    models.CharField(db_index=True, default="ALL", max_length=10),
                ),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "last_computed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_cache",
                        to="core.alumno",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_computed_at"],
                "indexes": [
                    models.Index(
                        fields=[
                            "alumno",
                            "cache_type",
                            "sport",
                            "start_date",
                            "end_date",
                        ],
                        name="analytics_a_alumno__874046_idx",
                    )
                ],
                "unique_together": {
                    ("alumno", "cache_type", "sport", "start_date", "end_date")
                },
            },
        ),
    ]
