name: Task
description: Standard development task
title: "[TASK] "
labels: ["task"]
body:
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What are we trying to achieve?
    validations:
      required: true
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this works?
    validations:
      required: true
  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
